/*
 * Copyright 2026 Oracle and/or its affiliates
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.dbn.liquibase.execution.ui;

import com.dbn.common.icon.Icons;
import com.dbn.common.task.TaskStatus;
import com.dbn.common.ui.form.DBNFormBase;
import com.dbn.common.ui.util.Borders;
import com.dbn.common.util.Documents;
import com.dbn.common.util.Editors;
import com.dbn.common.util.Viewers;
import com.dbn.connection.ConnectionHandler;
import com.dbn.language.sql.SQLFileType;
import com.dbn.language.sql.SQLLanguage;
import com.dbn.liquibase.DatabaseLiquibaseManager;
import com.dbn.liquibase.operation.LiquibaseOperationResult;
import com.intellij.openapi.editor.Document;
import com.intellij.openapi.editor.EditorSettings;
import com.intellij.openapi.editor.ex.EditorEx;
import com.intellij.openapi.project.Project;
import com.intellij.ui.JBColor;
import org.jetbrains.annotations.NotNull;

import javax.swing.JButton;
import javax.swing.JComponent;
import javax.swing.JPanel;

import static com.dbn.common.ui.form.field.JComponentFilter.array;
import static com.dbn.common.ui.util.Buttons.onButtonClick;

/** Read-only SQL viewer for SQL generated by a Liquibase execution. */
public class LiquibaseExecutionSqlForm extends DBNFormBase {
    private JPanel mainPanel;
    private JPanel actionsPanel;
    private JPanel viewerPanel;
    private JButton approveButton;
    private JButton rejectButton;
    private JPanel approvalButtonsPanel;
    private final LiquibaseOperationResult result;
    private final Document document;
    private final EditorEx viewer;

    public LiquibaseExecutionSqlForm(
            @NotNull DBNFormBase parent,
            @NotNull LiquibaseOperationResult result) {
        super(parent);
        this.result = result;

        actionsPanel.setBorder(Borders.lineBorder(JBColor.border(), 0, 0, 1, 0));
        updateFieldAvailability();
        onButtonClick(approveButton, e -> resumeOperation());
        onButtonClick(rejectButton, e -> cancelOperation());

        approveButton.setIcon(Icons.ACTION_APPROVE);
        rejectButton.setIcon(Icons.ACTION_REJECT);

        document = Documents.createDocument(result.getSqlOutput());
        ConnectionHandler connection = result.getConnection();
        Project project = result.getProject();
        viewer = Viewers.createViewer(document, project, null, SQLFileType.INSTANCE);
        viewer.setEmbeddedIntoDialogWrapper(false);
        viewer.setBorder(null);
        Editors.setEditorReadonly(viewer, true);
        Editors.initEditorHighlighter(viewer, SQLLanguage.INSTANCE, connection);
        Editors.updateEditorScrollPane(viewer, null);

        EditorSettings settings = viewer.getSettings();
        settings.setFoldingOutlineShown(false);
        settings.setLineMarkerAreaShown(false);
        settings.setLineNumbersShown(true);
        settings.setVirtualSpace(false);
        settings.setDndEnabled(false);
        settings.setRightMarginShown(false);
        settings.setUseSoftWraps(true);
        settings.setCaretRowShown(false);

        JComponent viewerComponent = viewer.getComponent();
        viewerComponent.setFocusable(false);
        viewerPanel.add(viewerComponent);
    }

    private void resumeOperation() {
        result.getInput().setApproved(true);
        updateFieldAvailability();

        DatabaseLiquibaseManager liquibaseManager = getLiquibaseManager();
        liquibaseManager.resumeOperation(result);
    }

    private void cancelOperation() {
        updateFieldAvailability();

        DatabaseLiquibaseManager liquibaseManager = getLiquibaseManager();
        liquibaseManager.cancelTask(result);
    }

    private @NotNull DatabaseLiquibaseManager getLiquibaseManager() {
        Project project = result.getProject();
        return DatabaseLiquibaseManager.getInstance(project);
    }

    @Override
    protected void initFieldAvailability() {
        getFieldAdapter().initFieldsVisibility(
                () -> isApprovalPending(),
                array(approvalButtonsPanel));
    }

    private boolean isApprovalPending() {
        return result.getStatus() == TaskStatus.PAUSED && result.getContext().requiresSqlPreview();
    }

    public void updateApprovalVisibility() {
        updateFieldAvailability();
    }

    public void setText(@NotNull CharSequence text) {
        Documents.setText(document, text);
    }

    @NotNull
    public EditorEx getViewer() {
        return viewer;
    }

    public void focusViewer() {
        viewer.getContentComponent().requestFocusInWindow();
    }

    @NotNull
    public JPanel getActionsPanel() {
        return actionsPanel;
    }

    @Override
    @NotNull
    public JPanel getMainComponent() {
        return mainPanel;
    }

    @Override
    public void disposeInner() {
        Editors.releaseEditor(viewer);
        super.disposeInner();
    }
}
