/*
 * Copyright 2026 Oracle and/or its affiliates
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.dbn.liquibase.execution.ui;

import com.dbn.common.ui.form.DBNFormBase;
import com.dbn.common.ui.util.Borders;
import com.dbn.common.util.Documents;
import com.dbn.common.util.Editors;
import com.dbn.common.util.Viewers;
import com.dbn.connection.ConnectionHandler;
import com.dbn.language.sql.SQLFileType;
import com.dbn.language.sql.SQLLanguage;
import com.dbn.liquibase.operation.LiquibaseOperationResult;
import com.intellij.openapi.editor.Document;
import com.intellij.openapi.editor.EditorSettings;
import com.intellij.openapi.editor.ex.EditorEx;
import com.intellij.openapi.project.Project;
import com.intellij.ui.JBColor;
import org.jetbrains.annotations.NotNull;

import javax.swing.JComponent;
import javax.swing.JPanel;
import java.awt.BorderLayout;

/** Read-only SQL viewer for SQL generated by a Liquibase execution. */
public class LiquibaseExecutionSqlPanel extends DBNFormBase {
    private final JPanel mainPanel = new JPanel(new BorderLayout());
    private final JPanel actionsPanel = new JPanel(new BorderLayout());
    private final JPanel viewerPanel = new JPanel(new BorderLayout());
    private final Document document;
    private final EditorEx viewer;

    public LiquibaseExecutionSqlPanel(
            @NotNull DBNFormBase parent,
            @NotNull LiquibaseOperationResult result) {
        super(parent);

        actionsPanel.setBorder(Borders.lineBorder(JBColor.border(), 0, 0, 1, 0));
        mainPanel.add(actionsPanel, BorderLayout.NORTH);
        mainPanel.add(viewerPanel, BorderLayout.CENTER);

        document = Documents.createDocument(result.getSqlOutput());
        ConnectionHandler connection = result.getConnection();
        Project project = result.getProject();
        viewer = Viewers.createViewer(document, project, null, SQLFileType.INSTANCE);
        viewer.setEmbeddedIntoDialogWrapper(false);
        viewer.setBorder(null);
        Editors.setEditorReadonly(viewer, true);
        Editors.initEditorHighlighter(viewer, SQLLanguage.INSTANCE, connection);
        Editors.updateEditorScrollPane(viewer, null);

        EditorSettings settings = viewer.getSettings();
        settings.setFoldingOutlineShown(false);
        settings.setLineMarkerAreaShown(false);
        settings.setLineNumbersShown(true);
        settings.setVirtualSpace(false);
        settings.setDndEnabled(false);
        settings.setRightMarginShown(false);
        settings.setUseSoftWraps(true);
        settings.setCaretRowShown(false);

        JComponent viewerComponent = viewer.getComponent();
        viewerComponent.setFocusable(false);
        viewerPanel.add(viewerComponent, BorderLayout.CENTER);
    }

    public void setText(@NotNull CharSequence text) {
        Documents.setText(document, text);
    }

    @NotNull
    public EditorEx getViewer() {
        return viewer;
    }

    @NotNull
    public JPanel getActionsPanel() {
        return actionsPanel;
    }

    @Override
    @NotNull
    public JPanel getMainComponent() {
        return mainPanel;
    }

    @Override
    public void disposeInner() {
        Editors.releaseEditor(viewer);
        super.disposeInner();
    }
}
