package com.dbn.mcp;

import com.dbn.common.template.TemplateUtilities;
import com.dbn.common.thread.Progress;
import com.dbn.common.ui.dialog.DBNDialog;
import com.dbn.common.util.Json;
import com.dbn.connection.ConnectionHandler;
import com.dbn.mcp.models.ToolDefinitionModel;
import com.intellij.openapi.application.ApplicationManager;
import com.intellij.openapi.progress.ProgressIndicator;
import com.intellij.openapi.project.Project;
import com.intellij.openapi.ui.Messages;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

import java.io.IOException;
import java.io.OutputStream;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.nio.file.StandardOpenOption;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Properties;
import java.util.function.Consumer;

public class McpServerInputDialog extends DBNDialog<McpServerInputForm> {
    private static final String TEMPLATE = "DBN - MCP Server Main";
    private static final String CONFIG = "mcp-config.properties";
    private static final String DIST = "mcp-dist";
    private static final String MCP_SDK = "io.modelcontextprotocol.sdk:mcp:0.11.1";
    private static final String JDBC = "com.oracle.database.jdbc:ojdbc11:23.8.0.25.04";

    private final Project project;

    protected McpServerInputDialog(@Nullable Project project) {
        super(project, "MCP Builder", true);
        this.project = project;
        init();
    }

    @NotNull @Override
    protected McpServerInputForm createForm() {
        return new McpServerInputForm(this);
    }

    @Override
    protected void doOKAction() {
        ConnectionHandler conn = getForm().getSelectedConnection();
        if (conn == null) {
            Messages.showErrorDialog(project, "Please select a connection", "No Connection");
            return;
        }

        BuildConfig cfg = createConfig(conn, getForm().getTools());
        String template = TemplateUtilities.generateCode(project, TEMPLATE, new Properties());

        super.doOKAction();
        build(cfg, template);
    }

    private BuildConfig createConfig(ConnectionHandler conn, List<ToolDefinitionModel> tools) {
        Path dir = project != null ? Paths.get(project.getBasePath()) : Paths.get(System.getProperty("user.home"));
        Properties p = new Properties();

        p.setProperty("mcp.url", safe(conn.getConnectionInfo().getUrl()));
        p.setProperty("mcp.user", safe(conn.getUserName()));
        p.setProperty("mcp.password", getPassword(conn));
        p.setProperty("mcp.serverName", "mcp-server");
        p.setProperty("mcp.serverVersion", "1.0.0");
        p.setProperty("mcp.tools.count", String.valueOf(tools.size()));

        for (int i = 0; i < tools.size(); i++) {
            ToolDefinitionModel t = tools.get(i);
            String prefix = "mcp.tools." + i + ".";
            p.setProperty(prefix + "name", safe(t.getName()));
            p.setProperty(prefix + "desc", safe(t.getDescription(), "SQL tool"));
            p.setProperty(prefix + "sql", safe(t.getSql(), "SELECT 1 FROM dual"));
            p.setProperty(prefix + "schema", safe(t.getJsonSchema(), "{}"));
        }

        return new BuildConfig(dir, dir.resolve(CONFIG), p);
    }

    private void build(BuildConfig cfg, String template) {
        try {
            Files.createDirectories(cfg.dir);
            try (OutputStream os = Files.newOutputStream(cfg.file, StandardOpenOption.CREATE, StandardOpenOption.TRUNCATE_EXISTING)) {
                cfg.props.store(os, "Generated by MCP Builder");
            }
        } catch (IOException e) {
            Messages.showErrorDialog(project, "Config write failed: " + e.getMessage(), "Error");
            return;
        }

        Progress.prompt(project, null, true, "Building MCP Server", "Maven build...", indicator -> {
            indicator.setIndeterminate(true);
            try {
                Path jar = MicroBuild.buildWithMaven(cfg.dir.resolve(DIST), MCP_SDK, JDBC, template, cfg.file, logger(indicator));
                showResult(cfg, jar);
            } catch (Exception e) {
                showError("Build failed: " + e.getMessage());
            }
        });
    }

    private Consumer<String> logger(ProgressIndicator ind) {
        long[] last = {0L};
        return line -> {
            if (line == null || System.nanoTime() - last[0] < 50_000_000L) return;
            last[0] = System.nanoTime();
            String t = line.replaceAll("\\p{Cntrl}", " ").replaceAll("\\s+", " ").trim();
            ind.setText2(t.length() > 140 ? t.substring(0, 140) + "…" : t);
        };
    }

    private void showResult(BuildConfig cfg, Path jar) {
        String name = cfg.props.getProperty("mcp.serverName", "mcp-server");
        String path = jar.toAbsolutePath().toString();
        ApplicationManager.getApplication().invokeLater(() ->
                new McpBuildResultDialog(project, cfg.file.toAbsolutePath().toString(), path,
                        buildJson(name, path, true), buildJson(name, path, false)).show());
    }

    private void showError(String msg) {
        ApplicationManager.getApplication().invokeLater(() -> Messages.showErrorDialog(project, msg, "MCP Build Error"));
    }

    private String getPassword(ConnectionHandler conn) {
        if (conn == null || conn.getAuthenticationInfo() == null) return "";
        char[] pwd = conn.getAuthenticationInfo().getPassword();
        return pwd != null ? new String(pwd) : "";
    }

    private String safe(String v) { return v != null ? v : ""; }
    private String safe(String v, String d) { return v != null && !v.isEmpty() ? v : d; }

    private String buildJson(String name, String jar, boolean full) {
        Map<String, Object> server = new LinkedHashMap<>();
        server.put("command", "java");
        server.put("args", List.of("-jar", jar));
        Map<String, Object> servers = Map.of(name, server);
        return Json.writeAsString(full ? Map.of("mcpServers", servers) : servers);
    }

    private static class BuildConfig {
        final Path dir, file;
        final Properties props;
        BuildConfig(Path dir, Path file, Properties props) { this.dir = dir; this.file = file; this.props = props; }
    }
}
