package com.dbn.mcp;

import com.dbn.common.ui.dialog.DBNDialog;
import com.dbn.common.thread.Progress;
import com.dbn.mcp.models.ToolDefinitionModel;
import com.intellij.openapi.application.ApplicationManager;
import com.intellij.openapi.project.Project;
import com.intellij.openapi.ui.Messages;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;
import com.intellij.openapi.ide.CopyPasteManager;
import com.intellij.ui.components.JBTabbedPane;
import com.intellij.ui.components.JBScrollPane;
import com.intellij.ui.components.JBTextArea;
import javax.swing.*;
import java.awt.*;
import java.awt.datatransfer.StringSelection;
import java.io.IOException;
import java.io.OutputStream;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.nio.file.StandardOpenOption;
import java.sql.SQLException;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.List;
import java.util.Properties;

public class McpServerInputDialog extends DBNDialog<McpServerInputForm> {
  private final Project project;

  protected McpServerInputDialog(@Nullable Project project) {
    super(project, "MCP Builder", true);
    this.project = project;
    init();
  }

  @Override
  protected @NotNull McpServerInputForm createForm() {

    return new McpServerInputForm(this);
  }

  @Override
  protected void doOKAction() {
    try {
      McpServerInputForm form = getForm();
      List<ToolDefinitionModel> toolDefinitionModel = form.getTools();


      String basePath = project != null ? project.getBasePath() : null;
      Path outDir = basePath != null ? Paths.get(basePath) : Paths.get(System.getProperty("user.home"));
      Path outFile = outDir.resolve("mcp-config.properties");

      // Build properties
      Properties props = new Properties();
      props.setProperty("mcp.url", form.getJdbcUrl() != null ? form.getJdbcUrl() : "");
      props.setProperty("mcp.user", form.getUsername() != null ? form.getUsername() : "");
      props.setProperty("mcp.password", form.getPassword() != null ? new String(form.getPassword()) : "");
      props.setProperty("mcp.serverName",   props.getProperty("mcp.serverName", "mcp-server"));
      props.setProperty("mcp.serverVersion", props.getProperty("mcp.serverVersion", "1.0.0"));

      //tools
      props.setProperty("mcp.tools.count", Integer.toString(toolDefinitionModel.size()));
      for(int i=0 ; i<toolDefinitionModel.size();i++){
        ToolDefinitionModel t = toolDefinitionModel.get(i);
        String prefix = "mcp.tools." + i + ".";
        props.setProperty(prefix + "name",   t.getName() != null ? t.getName() : "");
        props.setProperty(prefix + "desc",   t.getDescription() != null ? t.getDescription() : "Parameterized SELECT tool");
        props.setProperty(prefix + "sql",    t.getSql() != null ? t.getSql() : "SELECT 1 FROM dual");
        props.setProperty(prefix + "schema", t.getToolJsonSchema() != null ? t.getToolJsonSchema() : "{\"type\":\"object\",\"additionalProperties\":true}");
      }


      // Optional server identity (has defaults at runtime)

      super.doOKAction();

      // Write file
      Files.createDirectories(outDir);
      try (OutputStream os = Files.newOutputStream(outFile, StandardOpenOption.CREATE, StandardOpenOption.TRUNCATE_EXISTING)) {
        props.store(os, "Generated by MCP Builder UI");
      }

      // Close the input dialog now; perform the build in background with progress

      Progress.prompt(project, null, true, "Building MCP Server", "Invoking Maven (clean package)…", indicator -> {
        indicator.setIndeterminate(true);
        final long[] lastUpdateNanos = {0L};
        try {
          Path jarPath = MicroBuild.buildWithMaven(
                  outDir.resolve("mcp-dist"),
                  "io.modelcontextprotocol.sdk:mcp:0.11.1",
                  "com.oracle.database.jdbc:ojdbc11:23.8.0.25.04",
                  "\n" +
                  "import com.fasterxml.jackson.core.JsonProcessingException;\n" +
                  "import com.fasterxml.jackson.databind.ObjectMapper;\n" +
                  "import io.modelcontextprotocol.server.McpServer;\n" +
                  "import io.modelcontextprotocol.server.McpServerFeatures;\n" +
                  "import io.modelcontextprotocol.server.transport.StdioServerTransportProvider;\n" +
                  "import io.modelcontextprotocol.spec.McpSchema;\n" +
                  "\n" +
                  "import java.io.InputStream;\n" +
                  "import java.sql.*;\n" +
                  "import java.util.*;\n" +
                  "import java.util.stream.Collectors;\n" +
                  "import java.sql.Connection;\n" +
                  "import java.sql.DriverManager;\n" +
                  "import java.sql.PreparedStatement;\n" +
                  "import java.sql.ResultSet;\n" +
                  "import java.sql.ResultSetMetaData;\n" +
                  "import java.sql.SQLException;\n" +
                  "import java.util.HashMap;\n" +
                  "import java.util.Map;\n" +
                  "import java.util.ArrayList;\n" +
                  "import java.util.List;\n" +
                  "import oracle.jdbc.OraclePreparedStatement;\n" +
                  "\n" +
                  "public class Main {\n" +
                  "\n" +
                  "    public static void main(String[] args) throws Exception {\n" +
                  "      // Load configuration from properties (with -D overrides)\n" +
                  "      Properties cfg = new Properties();\n" +
                  "      try (InputStream in = Main.class.getResourceAsStream(\"/mcp-config.properties\")) {\n" +
                  "        if (in != null) cfg.load(in);\n" +
                  "      }\n" +
                  "      String url = System.getProperty(\"mcp.url\", cfg.getProperty(\"mcp.url\"));\n" +
                  "      String password = System.getProperty(\"mcp.password\", cfg.getProperty(\"mcp.password\"));\n" +
                  "      String user = System.getProperty(\"mcp.user\", cfg.getProperty(\"mcp.user\"));\n" +
                  "      String serverName = System.getProperty(\"mcp.serverName\", cfg.getProperty(\"mcp.serverName\", \"mcp-server\"));\n" +
                  "      String serverVersion = System.getProperty(\"mcp.serverVersion\", cfg.getProperty(\"mcp.serverVersion\", \"1.0.0\"));\n" +
                  "\n" +
                  "      // Load tools (indexed): mcp.tools.count and mcp.tools.{i}.name|desc|sql|schema\n" +
                  "      int toolCount = Integer.parseInt(System.getProperty(\n" +
                  "              \"mcp.tools.count\",\n" +
                  "              cfg.getProperty(\"mcp.tools.count\", \"0\")));\n" +
                  "      java.util.List<McpServerFeatures.SyncToolSpecification> specs = new java.util.ArrayList<>();\n" +
                  "      for (int i = 0; i < toolCount; i++) {\n" +
                  "        String p = \"mcp.tools.\" + i + \".\";\n" +
                  "        String tName   = System.getProperty(p + \"name\",   cfg.getProperty(p + \"name\",   \"tool_\" + i));\n" +
                  "        String tDesc   = System.getProperty(p + \"desc\",   cfg.getProperty(p + \"desc\",   \"Parameterized SELECT tool\"));\n" +
                  "        String tSql    = System.getProperty(p + \"sql\",    cfg.getProperty(p + \"sql\",    \"SELECT 1 AS value FROM dual\"));\n" +
                  "        String tSchema = System.getProperty(p + \"schema\", cfg.getProperty(p + \"schema\", \"{\\\"type\\\":\\\"object\\\",\\\"additionalProperties\\\":true}\"));\n" +
                  "        specs.add(createTool(tName, tDesc, tSchema, new DbDetails(url, user, password), tSql));\n" +
                  "      }\n" +
                  "      // Backwards-compat: fall back to single-tool props if none indexed\n" +
                  "      if (specs.isEmpty()) {\n" +
                  "        String tName   = System.getProperty(\"mcp.toolName\", cfg.getProperty(\"mcp.toolName\", \"run_select\"));\n" +
                  "        String tDesc   = System.getProperty(\"mcp.toolDesc\", cfg.getProperty(\"mcp.toolDesc\", \"Parameterized SELECT tool\"));\n" +
                  "        String tSql    = System.getProperty(\"tool.sql\",    cfg.getProperty(\"tool.sql\",    \"SELECT 1 AS value FROM dual\"));\n" +
                  "        String tSchema = System.getProperty(\"tool.schema\", cfg.getProperty(\"tool.schema\", \"{\\\"type\\\":\\\"object\\\",\\\"additionalProperties\\\":true}\"));\n" +
                  "        specs.add(createTool(tName, tDesc, tSchema, new DbDetails(url, user, password), tSql));\n" +
                  "      }\n" +
                  "\n" +
                  "      // Set up stdio transport and start server with all tools\n" +
                  "      StdioServerTransportProvider transport = new StdioServerTransportProvider(new ObjectMapper());\n" +
                  "      McpServer.sync(transport)\n" +
                  "              .serverInfo(serverName, serverVersion)\n" +
                  "              .capabilities(McpSchema.ServerCapabilities.builder()\n" +
                  "                      .tools(true)\n" +
                  "                      .logging()\n" +
                  "                      .build())\n" +
                  "              .tools(specs.toArray(new McpServerFeatures.SyncToolSpecification[0]))\n" +
                  "              .build();\n" +
                  "\n" +
                  "    }\n" +
                  "\n" +
                  "  private static McpServerFeatures.SyncToolSpecification createTool(String toolName, String toolDesc, String schema, DbDetails db, String sql) {\n" +
                  "    McpSchema.Tool tool = new McpSchema.Tool(toolName, toolDesc, schema);\n" +
                  "    return new McpServerFeatures.SyncToolSpecification(tool, (e, request) -> {\n" +
                  "        try (Connection conn = DriverManager.getConnection(db.url(), db.user(), db.password());\n" +
                  "             OraclePreparedStatement ps = (OraclePreparedStatement) conn.prepareStatement(sql)) {\n" +
                  "          // Dynamically bind all provided parameters by name\n" +
                  "          for (Map.Entry<String, Object> en : request.entrySet()) {\n" +
                  "            ps.setObjectAtName(en.getKey(), en.getValue());\n" +
                  "          }\n" +

          "            // Execute query and build result list\n" +
                  "            try (ResultSet rs = ps.executeQuery()) {\n" +
                  "                List<Map<String, Object>> rows = new ArrayList<>();\n" +
                  "                ResultSetMetaData md = rs.getMetaData();\n" +
                  "                int colCount = md.getColumnCount();\n" +
                  "                while (rs.next()) {\n" +
                  "                    Map<String, Object> row = new HashMap<>();\n" +
                  "                    for (int i = 1; i <= colCount; i++) {\n" +
                  "                        row.put(md.getColumnLabel(i), rs.getObject(i));\n" +
                  "                    }\n" +
                  "                    rows.add(row);\n" +
                  "                }\n" +
                  "                String json = new ObjectMapper().writeValueAsString(rows);\n" +
                  "                return new McpSchema.CallToolResult(List.of(new McpSchema.TextContent(json)), false);\n" +
                  "            } catch (JsonProcessingException ex) {\n" +
                  "                throw new RuntimeException(ex);\n" +
                  "            }\n" +
                  "        } catch (SQLException ex) {\n" +
                  "            return new McpSchema.CallToolResult(ex.getMessage(), true);\n" +
                  "        }\n" +
                  "    });\n" +
                  "  }\n" +
                  "\n" +
                  "  public static class DbDetails {\n" +
                  "    String url;\n" +
                  "    String user;\n" +
                  "    String password;\n" +
                  "    public DbDetails(String url, String user, String password) {\n" +
                  "      this.url = url;\n" +
                  "      this.user = user;\n" +
                  "      this.password = password;\n" +
                  "    }\n" +
                  "    String url(){ return url; }\n" +
                  "    String user(){ return user; }\n" +
                  "    String password(){ return password; }\n" +
                  "  }\n" +
                  "\n" +
                  "}\n",
                  outFile,
                  line -> {
                    if (line == null) return;
                    // Throttle to avoid spamming the UI
                    long now = System.nanoTime();
                    if (now - lastUpdateNanos[0] < 50_000_000L) { // 50 ms
                      return;
                    }
                    lastUpdateNanos[0] = now;
                    // Sanitize control/ANSI chars and trim length for a compact progress line
                    String clean = line
                            .replaceAll("\\p{Cntrl}", " ")
                            .replaceAll("\\s+", " ")
                            .trim();
                    if (clean.length() > 140) clean = clean.substring(0, 140) + "…";
                    indicator.setText2(clean);
                  }
          );

          // Prepare Claude Desktop config templates pointing to the built JAR
          String serverNameForClaude = props.getProperty("mcp.serverName", "mcp-db-select");
          String jarPathStr = jarPath.toAbsolutePath().toString();
          String jarPathJson = jarPathStr.replace("\\", "\\\\");

          String claudeFragmentJson = "{\n" +
                  "  \"" + serverNameForClaude + "\": {\n" +
                  "    \"command\": \"java\",\n" +
                  "    \"args\": [\n" +
                  "      \"-jar\",\n" +
                  "      \"" + jarPathJson + "\"\n" +
                  "    ]\n" +
                  "  }\n" +
                  "}";

          String claudeFullJson = "{\n" +
                  "  \"mcpServers\": " + claudeFragmentJson + "\n" +
                  "}";

          ApplicationManager.getApplication().invokeLater(() -> {
            new ClaudeConfigDialog(
                project,
                outFile.toAbsolutePath().toString(),
                jarPath.toAbsolutePath().toString(),
                claudeFullJson,
                claudeFragmentJson
            ).show();
          });
        } catch (Exception e) {
          ApplicationManager.getApplication().invokeLater(() ->
                  Messages.showErrorDialog(project, "Maven build failed: " + e.getMessage(), "MCP Build Error")
          );
        }
      });
    } catch (IOException ex) {
      Messages.showErrorDialog(
        (project != null ? project : null),
        "Failed to write mcp-config.properties:\n" + ex.getMessage(),
        "MCP Config Error"
      );
    }
  }
  // --- Claude config dialog ---
  private static final class ClaudeConfigDialog extends com.intellij.openapi.ui.DialogWrapper {
      private final Project project;
      private final String propsPath;
      private final String jarPath;
      private final String fullJson;
      private final String fragmentJson;

      protected ClaudeConfigDialog(Project project, String propsPath, String jarPath, String fullJson, String fragmentJson) {
          super(project);
          this.project = project;
          this.propsPath = propsPath;
          this.jarPath = jarPath;
          this.fullJson = fullJson;
          this.fragmentJson = fragmentJson;
          setTitle("MCP Build Complete");
          init();
      }

      @Override
      protected JComponent createCenterPanel() {
          JPanel panel = new JPanel(new BorderLayout(8, 8));

          String headerHtml = "<html>"
                  + "<b>Here is the MCP server entry to add in your MCP client config.</b><br>"
                  + "Saved properties: " + escapeHtml(propsPath) + "<br>"
                  + "Built JAR: " + escapeHtml(jarPath)
                  + "</html>";
          JLabel header = new JLabel(headerHtml);
          panel.add(header, BorderLayout.NORTH);

          JBTabbedPane tabs = new JBTabbedPane();
          tabs.addTab("Full file", createTab(fullJson));
          tabs.addTab("Fragment", createTab(fragmentJson));
          panel.add(tabs, BorderLayout.CENTER);

          return panel;
      }

      private JComponent createTab(String text) {
          JBTextArea area = new JBTextArea(text);
          area.setEditable(false);
          area.setLineWrap(false);
          area.setFont(new Font(Font.MONOSPACED, Font.PLAIN, 12));
          JBScrollPane scroll = new JBScrollPane(area);

          JPanel container = new JPanel(new BorderLayout());
          container.add(scroll, BorderLayout.CENTER);

          JButton copy = new JButton("Copy to Clipboard");
          copy.addActionListener(e ->
                  CopyPasteManager.getInstance().setContents(new StringSelection(text)));
          JPanel south = new JPanel(new FlowLayout(FlowLayout.RIGHT));
          south.add(copy);
          container.add(south, BorderLayout.SOUTH);

          return container;
      }

      private static String escapeHtml(String s) {
          return s == null ? "" : s.replace("&", "&amp;")
                  .replace("<", "&lt;")
                  .replace(">", "&gt;");
      }
  }
}
