// Generated by JFlex 1.9.1 http://jflex.de/  (tweaked for IntelliJ platform)
// source: postgres_psql_parser.flex

package com.dbn.language.psql.dialect.postgres;

import com.dbn.language.common.SharedTokenTypeBundle;
import com.dbn.language.common.TokenTypeBundle;
import com.intellij.lexer.FlexLexer;
import com.intellij.psi.tree.IElementType;


public final class PostgresPSQLParserFlexLexer implements FlexLexer {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;
  public static final int DIV = 2;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0,  0,  0, 0
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\1\u0100\1\u0200\1\u0300\1\u0400\1\u0500\1\u0600\1\u0700"+
    "\1\u0800\1\u0900\1\u0a00\1\u0b00\1\u0c00\1\u0d00\1\u0e00\1\u0f00"+
    "\1\u1000\1\u1100\1\u1200\1\u1300\1\u1400\1\u1100\1\u1500\1\u1600"+
    "\1\u1700\1\u1800\1\u1900\1\u1a00\1\u1b00\1\u1c00\1\u1100\1\u1d00"+
    "\1\u1e00\1\u1f00\12\u2000\1\u2100\1\u2200\1\u2300\1\u2000\1\u2400"+
    "\1\u2500\2\u2000\31\u1100\1\u2600\126\u1100\1\u2700\1\u1100\1\u2800"+
    "\1\u2900\1\u2a00\1\u2b00\1\u2c00\1\u2d00\53\u1100\1\u2e00\10\u2f00"+
    "\31\u2000\1\u1100\1\u3000\1\u3100\1\u1100\1\u3200\1\u3300\1\u3400"+
    "\1\u3500\1\u3600\1\u3700\1\u3800\1\u3900\1\u3a00\1\u1100\1\u3b00"+
    "\1\u3c00\1\u3d00\1\u3e00\1\u3f00\1\u4000\1\u4100\1\u4200\1\u4300"+
    "\1\u4400\1\u4500\1\u4600\1\u4700\1\u4800\1\u4900\1\u4a00\1\u4b00"+
    "\1\u4c00\1\u4d00\1\u4e00\1\u4f00\1\u5000\1\u5100\1\u5200\1\u5300"+
    "\3\u1100\1\u5400\1\u5500\1\u5600\11\u2000\1\u5700\4\u1100\1\u5800"+
    "\16\u1100\1\u5900\2\u1100\1\u5a00\32\u2000\1\u5b00\6\u2000\2\u1100"+
    "\1\u5c00\1\u5d00\1\u2000\1\u5e00\1\u5f00\1\u6000\27\u1100\1\u6100"+
    "\4\u1100\1\u6200\1\u6300\41\u2000\1\u6400\1\u1100\1\u6500\1\u6600"+
    "\11\u2000\1\u6700\17\u2000\1\u6800\2\u2000\1\u6900\1\u2000\1\u6a00"+
    "\1\u6b00\1\u2000\1\u6c00\1\u6d00\1\u6e00\1\u6f00\2\u2000\1\u7000"+
    "\4\u2000\1\u7100\1\u7200\1\u7300\1\u7400\1\u2000\1\u7500\1\u7600"+
    "\1\u2000\1\u7700\1\u7800\1\u7900\2\u2000\1\u7a00\1\u2000\1\u7b00"+
    "\14\u2000\1\u6800\4\u2000\246\u1100\1\u7c00\20\u1100\1\u7d00\1\u7e00"+
    "\25\u1100\1\u7f00\34\u1100\1\u8000\2\u1100\1\u8100\11\u2000\2\u1100"+
    "\1\u8200\5\u2000\23\u1100\1\u8300\17\u1100\1\u8400\u0adc\u2000\1\u8500"+
    "\1\u8600\u02fe\u2000";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\1\3\1\4\1\2\16\0\4\5"+
    "\1\1\1\6\1\7\1\10\1\11\1\12\1\13\1\14"+
    "\1\15\1\16\1\17\1\20\1\21\1\22\1\23\1\24"+
    "\1\25\1\26\1\27\1\30\1\31\1\32\1\33\1\34"+
    "\1\35\1\36\1\37\1\40\1\41\1\42\1\43\1\5"+
    "\1\44\1\45\1\46\1\47\1\50\1\51\1\52\1\53"+
    "\1\54\1\55\1\56\1\57\1\60\1\61\1\62\1\63"+
    "\1\64\1\11\1\65\1\66\1\67\1\70\1\11\1\71"+
    "\1\72\1\73\1\11\1\74\1\75\1\76\1\5\1\77"+
    "\1\5\1\45\1\46\1\47\1\50\1\51\1\52\1\53"+
    "\1\54\1\55\1\56\1\57\1\60\1\61\1\62\1\63"+
    "\1\64\1\11\1\65\1\66\1\67\1\70\1\11\1\71"+
    "\1\72\1\73\1\11\1\100\1\101\1\102\1\5\6\0"+
    "\1\103\32\0\2\5\4\11\4\5\1\11\2\5\1\0"+
    "\7\5\1\11\4\5\1\11\5\5\27\11\1\5\37\11"+
    "\1\5\70\11\2\55\115\11\1\66\u0142\11\4\5\14\11"+
    "\16\5\5\11\7\5\1\11\1\5\1\11\21\5\160\0"+
    "\5\11\1\5\2\11\2\5\4\11\1\5\1\11\6\5"+
    "\1\11\1\5\3\11\1\5\1\11\1\5\24\11\1\5"+
    "\123\11\1\5\213\11\1\5\5\0\2\5\246\11\1\5"+
    "\46\11\2\5\1\11\6\5\51\11\6\5\1\11\1\5"+
    "\55\0\1\5\1\0\1\5\2\0\1\5\2\0\1\5"+
    "\1\0\10\5\33\11\4\5\4\11\15\5\6\0\5\5"+
    "\1\11\4\5\13\0\1\5\1\0\3\5\53\11\37\0"+
    "\4\5\2\11\1\0\143\11\1\5\1\11\10\0\1\5"+
    "\6\0\2\11\2\0\1\5\4\0\2\11\12\0\3\11"+
    "\2\5\1\11\17\5\1\0\1\11\1\0\36\11\33\0"+
    "\2\5\131\11\13\0\1\11\16\5\12\0\41\11\11\0"+
    "\2\11\4\5\1\11\2\5\1\0\30\11\4\0\1\11"+
    "\11\0\1\11\3\0\1\11\5\0\22\5\31\11\3\0"+
    "\4\5\13\11\5\5\30\11\1\5\6\11\1\5\2\0"+
    "\5\5\11\0\52\11\72\0\66\11\3\0\1\11\22\0"+
    "\1\11\7\0\12\11\2\0\2\5\12\0\1\5\20\11"+
    "\3\0\1\5\10\11\2\5\2\11\2\5\26\11\1\5"+
    "\7\11\1\5\1\11\3\5\4\11\2\5\1\0\1\11"+
    "\7\0\2\5\2\0\2\5\3\0\1\11\10\5\1\0"+
    "\4\5\2\11\1\5\3\11\2\0\2\5\12\0\4\11"+
    "\7\5\2\11\1\5\1\0\2\5\3\0\1\5\6\11"+
    "\4\5\2\11\2\5\26\11\1\5\7\11\1\5\2\11"+
    "\1\5\2\11\1\5\2\11\2\5\1\0\1\5\5\0"+
    "\4\5\2\0\2\5\3\0\3\5\1\0\7\5\4\11"+
    "\1\5\1\11\7\5\14\0\3\11\1\0\13\5\3\0"+
    "\1\5\11\11\1\5\3\11\1\5\26\11\1\5\7\11"+
    "\1\5\2\11\1\5\5\11\2\5\1\0\1\11\10\0"+
    "\1\5\3\0\1\5\3\0\2\5\1\11\17\5\2\11"+
    "\2\0\2\5\12\0\1\5\1\11\7\5\1\11\6\0"+
    "\1\5\3\0\1\5\10\11\2\5\2\11\2\5\26\11"+
    "\1\5\7\11\1\5\2\11\1\5\5\11\2\5\1\0"+
    "\1\11\7\0\2\5\2\0\2\5\3\0\7\5\3\0"+
    "\4\5\2\11\1\5\3\11\2\0\2\5\12\0\1\5"+
    "\1\11\20\5\1\0\1\11\1\5\6\11\3\5\3\11"+
    "\1\5\4\11\3\5\2\11\1\5\1\11\1\5\2\11"+
    "\3\5\2\11\3\5\3\11\3\5\14\11\4\5\5\0"+
    "\3\5\3\0\1\5\4\0\2\5\1\11\6\5\1\0"+
    "\16\5\12\0\11\5\1\11\6\5\5\0\10\11\1\5"+
    "\3\11\1\5\27\11\1\5\20\11\2\5\1\0\1\11"+
    "\7\0\1\5\3\0\1\5\4\0\7\5\2\0\1\5"+
    "\3\11\2\5\1\11\2\5\2\11\2\0\2\5\12\0"+
    "\20\5\1\11\3\0\1\5\10\11\1\5\3\11\1\5"+
    "\27\11\1\5\12\11\1\5\5\11\2\5\1\0\1\11"+
    "\7\0\1\5\3\0\1\5\4\0\7\5\2\0\6\5"+
    "\2\11\1\5\2\11\2\0\2\5\12\0\1\5\2\11"+
    "\1\0\14\5\4\0\11\11\1\5\3\11\1\5\51\11"+
    "\2\0\1\11\7\0\1\5\3\0\1\5\4\0\1\11"+
    "\5\5\3\11\1\0\7\5\3\11\2\0\2\5\12\0"+
    "\12\5\6\11\1\5\3\0\1\5\22\11\3\5\30\11"+
    "\1\5\11\11\1\5\1\11\2\5\7\11\3\5\1\0"+
    "\4\5\6\0\1\5\1\0\1\5\10\0\6\5\12\0"+
    "\2\5\2\0\15\5\60\11\1\0\2\11\7\0\4\5"+
    "\10\11\10\0\1\5\12\0\47\5\2\11\1\5\1\11"+
    "\1\5\5\11\1\5\30\11\1\5\1\11\1\5\12\11"+
    "\1\0\2\11\11\0\1\11\2\5\5\11\1\5\1\11"+
    "\1\5\7\0\1\5\12\0\2\5\4\11\40\5\1\11"+
    "\27\5\2\0\6\5\12\0\13\5\1\0\1\5\1\0"+
    "\1\5\1\0\4\5\2\0\10\11\1\5\44\11\4\5"+
    "\24\0\1\5\2\0\5\11\13\0\1\5\44\0\11\5"+
    "\1\0\71\5\53\11\24\0\1\11\12\0\6\5\6\11"+
    "\4\0\4\11\3\0\1\11\3\0\2\11\7\0\3\11"+
    "\4\0\15\11\14\0\1\11\17\0\2\5\46\11\1\5"+
    "\1\11\5\5\1\11\2\5\53\11\1\5\u014d\11\1\5"+
    "\4\11\2\5\7\11\1\5\1\11\1\5\4\11\2\5"+
    "\51\11\1\5\4\11\2\5\41\11\1\5\4\11\2\5"+
    "\7\11\1\5\1\11\1\5\4\11\2\5\17\11\1\5"+
    "\71\11\1\5\4\11\2\5\103\11\2\5\3\0\40\5"+
    "\20\11\20\5\126\11\2\5\6\11\3\5\u016c\11\2\5"+
    "\21\11\1\5\32\11\5\5\113\11\3\5\13\11\7\5"+
    "\22\11\4\0\11\5\23\11\3\0\13\5\22\11\2\0"+
    "\14\5\15\11\1\5\3\11\1\5\2\0\14\5\64\11"+
    "\40\0\3\5\1\11\3\5\2\11\1\0\2\5\12\0"+
    "\41\5\17\0\6\5\131\11\7\5\5\11\2\0\42\11"+
    "\1\0\1\11\5\5\106\11\12\5\37\11\1\5\14\0"+
    "\4\5\14\0\12\5\12\0\36\11\2\5\5\11\13\5"+
    "\54\11\4\5\32\11\6\5\12\0\46\5\27\11\5\0"+
    "\4\5\65\11\12\0\1\5\35\0\2\5\13\0\6\5"+
    "\12\0\15\5\1\11\10\5\16\0\1\5\20\0\61\5"+
    "\5\0\57\11\21\0\10\11\3\5\12\0\21\5\11\0"+
    "\14\5\3\0\36\11\15\0\2\11\12\0\54\11\16\0"+
    "\14\5\44\11\24\0\10\5\12\0\3\5\3\11\12\0"+
    "\44\11\2\5\13\11\5\5\53\11\2\5\3\11\20\5"+
    "\3\0\1\5\25\0\4\11\1\0\6\11\1\0\2\11"+
    "\3\0\1\11\5\5\300\11\100\0\26\11\2\5\6\11"+
    "\2\5\46\11\2\5\6\11\2\5\10\11\1\5\1\11"+
    "\1\5\1\11\1\5\1\11\1\5\37\11\2\5\65\11"+
    "\1\5\7\11\1\5\1\11\3\5\3\11\1\5\7\11"+
    "\3\5\4\11\2\5\6\11\4\5\15\11\5\5\3\11"+
    "\1\5\7\11\16\5\5\0\30\5\2\3\5\0\20\5"+
    "\2\11\23\5\1\11\13\5\5\0\1\5\12\0\1\5"+
    "\1\11\15\5\1\11\20\5\15\11\3\5\41\11\17\5"+
    "\15\0\4\5\1\0\3\5\14\0\21\5\1\11\4\5"+
    "\1\11\2\5\12\11\1\5\1\11\3\5\5\11\6\5"+
    "\1\11\1\5\1\11\1\5\1\11\1\5\1\57\3\11"+
    "\1\5\13\11\2\5\4\11\5\5\5\11\4\5\1\11"+
    "\21\5\51\11\u0177\5\345\11\6\5\4\11\3\0\2\11"+
    "\14\5\46\11\1\5\1\11\5\5\1\11\2\5\70\11"+
    "\7\5\1\11\17\5\1\0\27\11\11\5\7\11\1\5"+
    "\7\11\1\5\7\11\1\5\7\11\1\5\7\11\1\5"+
    "\7\11\1\5\7\11\1\5\7\11\1\5\40\0\57\5"+
    "\1\11\325\5\3\11\31\5\11\11\6\0\1\5\5\11"+
    "\2\5\5\11\4\5\126\11\2\5\2\0\2\5\3\11"+
    "\1\5\132\11\1\5\4\11\5\5\53\11\1\5\136\11"+
    "\21\5\40\11\60\5\320\11\100\5\215\11\103\5\56\11"+
    "\2\5\15\11\3\5\20\11\12\0\2\11\24\5\57\11"+
    "\1\0\4\5\12\0\1\5\37\11\2\0\120\11\2\0"+
    "\45\5\11\11\2\5\147\11\2\5\103\11\2\5\2\11"+
    "\1\5\1\11\1\5\10\11\25\5\20\11\1\0\3\11"+
    "\1\0\4\11\1\0\27\11\5\0\4\5\1\0\13\5"+
    "\1\11\7\5\64\11\14\5\2\0\62\11\22\0\12\5"+
    "\12\0\6\5\22\0\6\11\3\5\1\11\1\5\2\11"+
    "\13\0\34\11\10\0\2\5\27\11\15\0\14\5\35\11"+
    "\3\5\4\0\57\11\16\0\16\5\1\11\12\0\6\5"+
    "\5\11\1\0\12\11\12\0\5\11\1\5\51\11\16\0"+
    "\11\5\3\11\1\0\10\11\2\0\2\5\12\0\6\5"+
    "\27\11\3\5\1\11\3\0\62\11\1\0\1\11\3\0"+
    "\2\11\2\0\5\11\2\0\1\11\1\0\1\11\30\5"+
    "\3\11\2\5\13\11\5\0\2\5\3\11\2\0\12\5"+
    "\6\11\2\5\6\11\2\5\6\11\11\5\7\11\1\5"+
    "\7\11\1\5\53\11\1\5\16\11\6\5\163\11\10\0"+
    "\1\5\2\0\2\5\12\0\6\5\244\11\14\5\27\11"+
    "\4\5\61\11\4\5\u0100\3\156\11\2\5\152\11\46\5"+
    "\7\11\14\5\5\11\5\5\1\11\1\0\12\11\1\5"+
    "\15\11\1\5\5\11\1\5\1\11\1\5\2\11\1\5"+
    "\2\11\1\5\154\11\41\5\153\11\22\5\100\11\2\5"+
    "\66\11\50\5\15\11\3\5\20\0\20\5\20\0\3\5"+
    "\2\11\30\5\3\11\31\5\1\11\6\5\5\11\1\5"+
    "\207\11\2\5\1\0\4\5\1\11\13\5\12\0\7\5"+
    "\32\11\4\5\1\11\1\5\32\11\13\5\131\11\3\5"+
    "\6\11\2\5\6\11\2\5\6\11\2\5\3\11\3\5"+
    "\2\11\3\5\2\11\22\5\3\0\4\5\14\11\1\5"+
    "\32\11\1\5\23\11\1\5\2\11\1\5\17\11\2\5"+
    "\16\11\42\5\173\11\105\5\65\11\210\5\1\0\202\5"+
    "\35\11\3\5\61\11\17\5\1\0\37\5\40\11\15\5"+
    "\36\11\5\5\46\11\5\0\5\5\36\11\2\5\44\11"+
    "\4\5\10\11\1\5\5\11\52\5\236\11\2\5\12\0"+
    "\6\5\44\11\4\5\44\11\4\5\50\11\10\5\64\11"+
    "\14\5\13\11\1\5\17\11\1\5\7\11\1\5\2\11"+
    "\1\5\13\11\1\5\17\11\1\5\7\11\1\5\2\11"+
    "\3\5\64\11\14\5\67\11\11\5\26\11\12\5\10\11"+
    "\30\5\6\11\1\5\52\11\1\5\11\11\105\5\6\11"+
    "\2\5\1\11\1\5\54\11\1\5\2\11\3\5\1\11"+
    "\2\5\27\11\12\5\27\11\11\5\37\11\101\5\23\11"+
    "\1\5\2\11\12\5\26\11\12\5\32\11\106\5\70\11"+
    "\6\5\2\11\100\5\1\11\3\0\1\5\2\0\5\5"+
    "\4\0\4\11\1\5\3\11\1\5\35\11\2\5\3\0"+
    "\4\5\1\0\40\5\35\11\3\5\35\11\43\5\10\11"+
    "\1\5\34\11\2\0\31\5\66\11\12\5\26\11\12\5"+
    "\23\11\15\5\22\11\156\5\111\11\67\5\63\11\15\5"+
    "\63\11\15\5\44\11\4\0\10\5\12\0\6\5\12\0"+
    "\34\11\3\5\5\0\1\5\27\11\372\5\52\11\1\5"+
    "\2\0\3\5\2\11\20\5\3\11\67\5\4\0\35\11"+
    "\12\5\1\11\10\5\26\11\13\0\37\5\22\11\4\0"+
    "\52\5\25\11\33\5\27\11\11\5\3\0\65\11\17\0"+
    "\37\5\13\0\2\11\2\0\1\11\11\5\4\0\55\11"+
    "\13\0\2\5\1\0\4\5\1\0\12\5\1\0\2\5"+
    "\31\11\7\5\12\0\6\5\3\0\44\11\16\0\1\5"+
    "\12\0\4\5\1\11\2\0\1\11\10\5\43\11\1\0"+
    "\2\5\1\11\11\5\3\0\60\11\16\0\4\11\4\5"+
    "\4\0\1\5\14\0\1\11\1\5\1\11\43\5\22\11"+
    "\1\5\31\11\14\0\6\5\1\0\2\11\1\0\76\5"+
    "\7\11\1\5\1\11\1\5\4\11\1\5\17\11\1\5"+
    "\12\11\7\5\57\11\14\0\5\5\12\0\6\5\4\0"+
    "\1\5\10\11\2\5\2\11\2\5\26\11\1\5\7\11"+
    "\1\5\2\11\1\5\5\11\1\5\2\0\1\11\7\0"+
    "\2\5\2\0\2\5\3\0\2\5\1\11\6\5\1\0"+
    "\5\5\5\11\2\0\2\5\7\0\3\5\5\0\13\5"+
    "\12\11\1\5\1\11\2\5\1\11\1\5\46\11\1\5"+
    "\1\11\11\0\1\5\1\0\2\5\1\0\1\5\4\0"+
    "\1\5\5\0\1\11\1\0\1\11\15\5\2\0\35\5"+
    "\65\11\22\0\4\11\5\5\12\0\4\5\1\0\3\11"+
    "\36\5\60\11\24\0\2\11\1\5\1\11\10\5\12\0"+
    "\246\5\57\11\7\0\2\5\11\0\27\5\4\11\2\0"+
    "\42\5\60\11\21\0\3\5\1\11\13\5\12\0\46\5"+
    "\53\11\15\0\1\11\7\5\12\0\6\5\24\0\34\5"+
    "\33\11\2\5\17\0\4\5\12\0\6\5\7\11\271\5"+
    "\54\11\17\0\145\5\100\11\12\0\25\5\10\11\2\5"+
    "\1\11\2\5\10\11\1\5\2\11\1\5\30\11\6\0"+
    "\1\5\2\0\2\5\4\0\1\11\1\0\1\11\2\0"+
    "\14\5\12\0\106\5\10\11\2\5\47\11\7\0\2\5"+
    "\7\0\1\11\1\5\1\11\1\0\33\5\1\11\12\0"+
    "\50\11\7\0\1\11\4\0\10\5\1\0\10\5\1\11"+
    "\13\0\56\11\20\0\3\5\1\11\22\5\111\11\307\5"+
    "\41\11\17\5\12\0\6\5\11\11\1\5\45\11\10\0"+
    "\1\5\10\0\1\11\17\5\12\0\30\5\36\11\2\5"+
    "\26\0\1\5\16\0\111\5\7\11\1\5\2\11\1\5"+
    "\46\11\6\0\3\5\1\0\1\5\2\0\1\5\7\0"+
    "\1\11\1\0\10\5\12\0\6\5\6\11\1\5\2\11"+
    "\1\5\40\11\5\0\1\5\2\0\1\5\5\0\1\11"+
    "\7\5\12\0\u0136\5\23\11\4\0\11\5\2\0\1\11"+
    "\1\0\15\11\1\5\42\11\7\0\3\5\5\0\15\5"+
    "\13\0\125\5\1\11\54\5\4\11\37\5\232\11\146\5"+
    "\157\11\21\5\304\11\u014c\5\141\11\17\5\60\11\21\0"+
    "\6\11\17\0\12\5\u019b\11\5\5\107\11\271\5\36\11"+
    "\34\0\306\5\71\11\7\5\37\11\1\5\12\0\6\5"+
    "\117\11\1\5\12\0\6\5\36\11\2\5\5\0\13\5"+
    "\60\11\7\0\11\5\4\11\14\5\12\0\11\5\25\11"+
    "\5\5\23\11\260\5\55\11\3\5\12\0\306\5\100\11"+
    "\200\5\113\11\4\5\1\0\1\11\67\0\7\5\4\0"+
    "\15\11\100\5\2\11\1\5\1\11\1\0\13\5\2\0"+
    "\16\5\370\11\10\5\326\11\51\5\12\11\u01e7\5\4\11"+
    "\1\5\7\11\1\5\2\11\1\5\43\11\17\5\1\11"+
    "\35\5\3\11\2\5\1\11\16\5\4\11\10\5\u018c\11"+
    "\4\5\153\11\5\5\15\11\3\5\11\11\7\5\12\11"+
    "\3\5\2\0\1\5\4\0\u014c\5\12\0\6\5\56\0"+
    "\2\5\27\0\u011e\5\5\0\3\5\26\0\2\5\7\0"+
    "\36\5\4\0\224\5\3\0\273\5\125\11\1\5\107\11"+
    "\1\5\2\11\2\5\1\11\2\5\2\11\2\5\4\11"+
    "\1\5\14\11\1\5\1\11\1\5\7\11\1\5\101\11"+
    "\1\5\4\11\2\5\10\11\1\5\7\11\1\5\34\11"+
    "\1\5\4\11\1\5\5\11\1\5\1\11\3\5\7\11"+
    "\1\5\u0154\11\2\5\31\11\1\5\31\11\1\5\37\11"+
    "\1\5\31\11\1\5\37\11\1\5\31\11\1\5\37\11"+
    "\1\5\31\11\1\5\37\11\1\5\31\11\1\5\10\11"+
    "\2\5\151\0\4\5\62\0\10\5\1\0\16\5\1\0"+
    "\26\5\5\0\1\5\17\0\120\5\37\11\6\5\6\11"+
    "\325\5\7\0\1\5\21\0\2\5\7\0\1\5\2\0"+
    "\1\5\5\0\5\5\76\11\41\5\1\0\160\5\55\11"+
    "\3\5\7\0\7\11\2\5\12\0\4\5\1\11\u0141\5"+
    "\36\11\1\0\21\5\54\11\16\0\5\5\1\11\320\5"+
    "\34\11\16\0\326\5\36\11\2\0\1\11\12\0\345\5"+
    "\7\11\1\5\4\11\1\5\2\11\1\5\17\11\1\5"+
    "\305\11\13\5\7\0\51\5\104\11\7\0\1\11\4\5"+
    "\12\0\u0156\5\1\11\117\5\4\11\1\5\33\11\1\5"+
    "\2\11\1\5\1\11\2\5\1\11\1\5\12\11\1\5"+
    "\4\11\1\5\1\11\1\5\1\11\6\5\1\11\4\5"+
    "\1\11\1\5\1\11\1\5\1\11\1\5\3\11\1\5"+
    "\2\11\1\5\1\11\2\5\1\11\1\5\1\11\1\5"+
    "\1\11\1\5\1\11\1\5\1\11\1\5\2\11\1\5"+
    "\1\11\2\5\4\11\1\5\7\11\1\5\4\11\1\5"+
    "\4\11\1\5\1\11\1\5\12\11\1\5\21\11\5\5"+
    "\3\11\1\5\5\11\1\5\21\11\104\5\340\11\40\5"+
    "\72\11\6\5\336\11\2\5\u0182\11\16\5\u0131\11\17\5"+
    "\156\11\242\5\36\11\342\5\113\11\5\5\u0160\11\121\5"+
    "\1\0\36\5\140\0\200\5\360\0\20\5";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[34560];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\1\1\4\1\1\1\5"+
    "\1\6\1\7\1\10\1\11\1\12\1\13\1\14\1\15"+
    "\1\16\1\17\1\20\1\21\1\22\1\23\1\24\1\25"+
    "\4\1\1\26\1\27\1\1\1\30\1\31\1\32\1\0"+
    "\1\33\1\6\1\34\1\35\1\36\1\37\3\0\1\40"+
    "\1\41\1\0\1\42\1\43\1\0\1\44\1\45\1\0"+
    "\1\46\3\0\15\1\1\0\1\47\2\0\1\37\1\0"+
    "\1\17\2\6\1\0\24\1\1\36\1\0\1\36\1\0"+
    "\25\1\1\37\11\1\1\0\25\1";

  private static int [] zzUnpackAction() {
    int [] result = new int[157];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\104\0\210\0\314\0\u0110\0\104\0\u0154\0\104"+
    "\0\u0198\0\104\0\104\0\104\0\104\0\104\0\u01dc\0\u0220"+
    "\0\u0264\0\u02a8\0\u02ec\0\104\0\u0330\0\u0374\0\u03b8\0\104"+
    "\0\u03fc\0\u0440\0\u0484\0\u04c8\0\104\0\104\0\u050c\0\104"+
    "\0\u0550\0\104\0\314\0\104\0\u0594\0\u05d8\0\104\0\u061c"+
    "\0\u0660\0\u06a4\0\u06e8\0\u072c\0\104\0\104\0\u0330\0\104"+
    "\0\104\0\u0374\0\104\0\104\0\u03b8\0\104\0\u0770\0\u07b4"+
    "\0\u07f8\0\u083c\0\u0880\0\u08c4\0\u0908\0\u094c\0\u0990\0\u09d4"+
    "\0\u0a18\0\u0a5c\0\u0aa0\0\u0ae4\0\u0b28\0\u0b6c\0\u0550\0\104"+
    "\0\u0bb0\0\u0bf4\0\u0c38\0\u0c7c\0\u0cc0\0\u0d04\0\u07f8\0\u0d48"+
    "\0\u0d8c\0\u0dd0\0\u0e14\0\u0e58\0\u0e9c\0\u0ee0\0\u0f24\0\u0f68"+
    "\0\u0fac\0\u0ff0\0\u1034\0\u1078\0\u10bc\0\u1100\0\u1144\0\u1188"+
    "\0\u11cc\0\u1210\0\u1254\0\u1298\0\u0bb0\0\u12dc\0\u12dc\0\u1320"+
    "\0\u1364\0\u13a8\0\u13ec\0\u1430\0\u1474\0\u14b8\0\u14fc\0\u1540"+
    "\0\u1584\0\u15c8\0\u160c\0\u1650\0\u1694\0\u16d8\0\u171c\0\u1760"+
    "\0\u17a4\0\u17e8\0\u182c\0\u1870\0\u18b4\0\104\0\u18f8\0\u193c"+
    "\0\u1980\0\u19c4\0\u1a08\0\u1a4c\0\u1a90\0\u1ad4\0\u1b18\0\u1b5c"+
    "\0\u1ba0\0\u1be4\0\u1c28\0\u1c6c\0\u1cb0\0\u1cf4\0\u1d38\0\u1d7c"+
    "\0\u1dc0\0\u1e04\0\u1e48\0\u1e8c\0\u1ed0\0\u1f14\0\u1f58\0\u1f9c"+
    "\0\u1fe0\0\u2024\0\u2068\0\u20ac\0\u20f0";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[157];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length() - 1;
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpacktrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\2\3\1\0\1\3\1\2\1\4\1\5\1\6"+
    "\1\7\1\10\1\2\1\11\1\12\1\13\1\14\1\15"+
    "\1\16\1\17\1\20\1\21\12\22\1\23\1\24\1\25"+
    "\1\26\1\27\1\30\1\7\1\31\2\7\1\32\10\7"+
    "\1\33\5\7\1\34\1\7\1\31\1\7\1\35\1\2"+
    "\1\36\1\37\1\40\1\41\1\42\106\0\2\3\1\0"+
    "\1\3\100\0\2\43\1\0\1\43\35\0\1\44\41\0"+
    "\7\5\1\2\74\5\1\7\7\0\2\7\13\0\12\7"+
    "\6\0\27\7\3\0\1\7\3\0\1\7\14\11\1\45"+
    "\67\11\22\0\1\46\104\0\1\47\1\0\12\50\64\0"+
    "\1\51\107\0\1\52\1\0\12\22\12\0\1\53\33\0"+
    "\2\54\1\0\1\54\32\0\1\55\2\0\1\56\42\0"+
    "\2\57\1\0\1\57\35\0\1\60\1\61\41\0\2\62"+
    "\1\0\1\62\35\0\1\63\1\64\41\0\2\65\1\0"+
    "\1\65\35\0\1\66\41\0\1\7\7\0\2\7\2\0"+
    "\1\67\10\0\12\7\6\0\27\7\3\0\1\7\3\0"+
    "\2\7\7\0\2\7\2\0\1\70\10\0\12\7\6\0"+
    "\27\7\3\0\1\7\3\0\2\7\7\0\2\7\2\0"+
    "\1\11\10\0\12\7\6\0\27\7\3\0\1\7\3\0"+
    "\2\7\7\0\2\7\1\0\1\71\11\0\12\7\6\0"+
    "\27\7\3\0\1\7\3\0\2\7\7\0\2\7\13\0"+
    "\12\7\6\0\1\72\1\73\1\74\1\75\1\76\1\7"+
    "\1\77\1\100\2\7\1\101\1\102\1\103\4\7\1\104"+
    "\1\105\1\106\3\7\3\0\1\7\3\0\1\7\1\0"+
    "\2\107\1\0\1\107\74\0\1\110\16\0\1\11\67\0"+
    "\2\46\1\0\101\46\25\0\12\50\11\0\1\111\1\112"+
    "\1\111\31\0\104\113\25\0\12\50\65\0\1\114\1\0"+
    "\1\114\2\0\12\115\46\0\2\54\1\0\1\54\35\0"+
    "\1\56\41\0\14\67\1\116\67\67\14\70\1\117\60\70"+
    "\1\120\6\70\14\0\1\70\67\0\1\7\7\0\2\7"+
    "\13\0\12\7\6\0\20\7\1\121\1\122\5\7\3\0"+
    "\1\7\3\0\2\7\7\0\2\7\13\0\12\7\6\0"+
    "\10\7\1\123\16\7\3\0\1\7\3\0\2\7\7\0"+
    "\2\7\13\0\12\7\6\0\17\7\1\124\7\7\3\0"+
    "\1\7\3\0\2\7\7\0\2\7\13\0\12\7\6\0"+
    "\4\7\1\125\22\7\3\0\1\7\3\0\2\7\7\0"+
    "\2\7\13\0\12\7\6\0\23\7\1\126\3\7\3\0"+
    "\1\7\3\0\2\7\7\0\2\7\13\0\12\7\6\0"+
    "\1\7\1\127\2\7\1\130\13\7\1\131\6\7\3\0"+
    "\1\7\3\0\2\7\7\0\2\7\13\0\12\7\6\0"+
    "\4\7\1\132\12\7\1\133\7\7\3\0\1\7\3\0"+
    "\2\7\7\0\2\7\13\0\12\7\6\0\4\7\1\134"+
    "\11\7\1\135\10\7\3\0\1\7\3\0\2\7\7\0"+
    "\2\7\13\0\12\7\6\0\1\136\26\7\3\0\1\7"+
    "\3\0\2\7\7\0\2\7\13\0\12\7\6\0\1\137"+
    "\26\7\3\0\1\7\3\0\2\7\7\0\2\7\13\0"+
    "\12\7\6\0\11\7\1\140\12\7\1\141\2\7\3\0"+
    "\1\7\3\0\2\7\7\0\2\7\13\0\12\7\6\0"+
    "\10\7\1\142\16\7\3\0\1\7\3\0\2\7\7\0"+
    "\2\7\13\0\12\7\6\0\2\7\1\143\6\7\1\140"+
    "\10\7\1\144\4\7\3\0\1\7\3\0\1\7\1\0"+
    "\2\145\1\0\1\145\117\0\1\146\1\0\1\146\2\0"+
    "\12\147\45\0\17\113\1\150\64\113\25\0\12\115\70\0"+
    "\1\52\1\0\12\115\61\0\1\67\67\0\2\70\3\0"+
    "\76\70\1\0\1\7\7\0\2\7\13\0\12\7\6\0"+
    "\14\7\1\151\12\7\3\0\1\7\3\0\2\7\7\0"+
    "\2\7\13\0\12\7\6\0\2\7\1\152\24\7\3\0"+
    "\1\7\3\0\2\7\7\0\2\7\13\0\12\7\6\0"+
    "\6\7\1\153\6\7\1\154\11\7\3\0\1\7\3\0"+
    "\2\7\7\0\2\7\13\0\1\7\1\155\6\7\1\156"+
    "\1\157\6\0\27\7\3\0\1\7\3\0\2\7\7\0"+
    "\2\7\13\0\12\7\6\0\2\7\1\133\24\7\3\0"+
    "\1\7\3\0\2\7\7\0\2\7\13\0\12\7\6\0"+
    "\2\7\1\160\24\7\3\0\1\7\3\0\2\7\7\0"+
    "\2\7\13\0\2\7\1\161\7\7\6\0\12\7\1\162"+
    "\14\7\3\0\1\7\3\0\2\7\7\0\2\7\13\0"+
    "\12\7\6\0\16\7\1\163\10\7\3\0\1\7\3\0"+
    "\2\7\7\0\2\7\13\0\12\7\6\0\4\7\1\164"+
    "\22\7\3\0\1\7\3\0\2\7\7\0\2\7\13\0"+
    "\12\7\6\0\1\7\1\165\25\7\3\0\1\7\3\0"+
    "\2\7\7\0\2\7\13\0\10\7\1\162\1\7\6\0"+
    "\27\7\3\0\1\7\3\0\2\7\7\0\2\7\13\0"+
    "\12\7\6\0\26\7\1\166\3\0\1\7\3\0\2\7"+
    "\7\0\2\7\13\0\12\7\6\0\10\7\1\167\16\7"+
    "\3\0\1\7\3\0\2\7\7\0\2\7\13\0\12\7"+
    "\6\0\22\7\1\170\4\7\3\0\1\7\3\0\2\7"+
    "\7\0\2\7\13\0\12\7\6\0\2\7\1\171\24\7"+
    "\3\0\1\7\3\0\2\7\7\0\2\7\13\0\12\7"+
    "\6\0\10\7\1\172\16\7\3\0\1\7\3\0\2\7"+
    "\7\0\2\7\13\0\12\7\6\0\4\7\1\173\22\7"+
    "\3\0\1\7\3\0\2\7\7\0\2\7\13\0\12\7"+
    "\6\0\21\7\1\174\5\7\3\0\1\7\3\0\2\7"+
    "\7\0\2\7\13\0\12\7\6\0\21\7\1\175\5\7"+
    "\3\0\1\7\3\0\2\7\7\0\2\7\13\0\12\7"+
    "\6\0\5\7\1\133\21\7\3\0\1\7\3\0\1\7"+
    "\25\0\12\147\45\0\17\113\1\150\4\113\1\176\57\113"+
    "\1\7\7\0\2\7\13\0\12\7\6\0\21\7\1\177"+
    "\5\7\3\0\1\7\3\0\2\7\7\0\2\7\13\0"+
    "\12\7\6\0\10\7\1\200\16\7\3\0\1\7\3\0"+
    "\2\7\7\0\2\7\13\0\5\7\1\162\4\7\6\0"+
    "\27\7\3\0\1\7\3\0\2\7\7\0\2\7\13\0"+
    "\12\7\6\0\1\201\26\7\3\0\1\7\3\0\2\7"+
    "\7\0\2\7\13\0\2\7\1\202\7\7\6\0\27\7"+
    "\3\0\1\7\3\0\2\7\7\0\2\7\13\0\5\7"+
    "\1\203\1\204\3\7\6\0\27\7\3\0\1\7\3\0"+
    "\2\7\7\0\2\7\13\0\3\7\1\175\6\7\6\0"+
    "\27\7\3\0\1\7\3\0\2\7\7\0\2\7\13\0"+
    "\12\7\6\0\11\7\1\205\1\206\14\7\3\0\1\7"+
    "\3\0\2\7\7\0\2\7\13\0\3\7\1\207\6\7"+
    "\6\0\27\7\3\0\1\7\3\0\2\7\2\210\1\0"+
    "\1\210\3\0\2\7\2\0\1\11\10\0\12\7\6\0"+
    "\27\7\3\0\1\7\3\0\2\7\7\0\2\7\13\0"+
    "\12\7\6\0\21\7\1\211\5\7\3\0\1\7\3\0"+
    "\2\7\7\0\2\7\13\0\12\7\6\0\4\7\1\212"+
    "\22\7\3\0\1\7\3\0\2\7\7\0\2\7\13\0"+
    "\12\7\6\0\20\7\1\213\6\7\3\0\1\7\3\0"+
    "\2\7\7\0\2\7\13\0\12\7\6\0\1\7\1\214"+
    "\25\7\3\0\1\7\3\0\2\7\7\0\2\7\13\0"+
    "\10\7\1\215\1\7\6\0\27\7\3\0\1\7\3\0"+
    "\2\7\7\0\2\7\13\0\12\7\6\0\10\7\1\216"+
    "\16\7\3\0\1\7\3\0\2\7\7\0\2\7\13\0"+
    "\12\7\6\0\2\7\1\217\15\7\1\220\6\7\3\0"+
    "\1\7\3\0\2\7\7\0\2\7\13\0\12\7\6\0"+
    "\21\7\1\162\5\7\3\0\1\7\3\0\2\7\7\0"+
    "\2\7\13\0\7\7\1\162\2\7\6\0\27\7\3\0"+
    "\1\7\3\0\2\7\7\0\2\7\13\0\6\7\1\221"+
    "\3\7\6\0\27\7\3\0\1\7\3\0\2\7\7\0"+
    "\2\7\13\0\2\7\1\162\7\7\6\0\27\7\3\0"+
    "\1\7\3\0\2\7\7\0\2\7\13\0\12\7\6\0"+
    "\2\7\1\222\24\7\3\0\1\7\3\0\2\7\7\0"+
    "\2\7\13\0\12\7\6\0\10\7\1\162\16\7\3\0"+
    "\1\7\3\0\2\7\7\0\2\7\13\0\12\7\6\0"+
    "\20\7\1\223\6\7\3\0\1\7\3\0\2\7\7\0"+
    "\2\7\13\0\5\7\1\224\4\7\6\0\27\7\3\0"+
    "\1\7\3\0\2\7\7\0\2\7\13\0\1\162\1\7"+
    "\1\162\7\7\6\0\27\7\3\0\1\7\3\0\2\7"+
    "\7\0\2\7\13\0\6\7\1\162\3\7\6\0\27\7"+
    "\3\0\1\7\3\0\2\7\7\0\2\7\13\0\12\7"+
    "\6\0\17\7\1\225\7\7\3\0\1\7\3\0\2\7"+
    "\7\0\2\7\13\0\12\7\6\0\20\7\1\162\6\7"+
    "\3\0\1\7\3\0\2\7\7\0\2\7\13\0\1\7"+
    "\1\175\10\7\6\0\27\7\3\0\1\7\3\0\1\7"+
    "\1\0\2\210\1\0\1\210\7\0\1\11\67\0\1\7"+
    "\7\0\2\7\13\0\12\7\6\0\22\7\1\226\4\7"+
    "\3\0\1\7\3\0\2\7\7\0\2\7\13\0\12\7"+
    "\6\0\12\7\1\162\14\7\3\0\1\7\3\0\2\7"+
    "\7\0\2\7\13\0\12\7\6\0\4\7\1\227\22\7"+
    "\3\0\1\7\3\0\2\7\7\0\2\7\13\0\12\7"+
    "\6\0\2\7\1\143\24\7\3\0\1\7\3\0\2\7"+
    "\7\0\2\7\13\0\12\7\6\0\20\7\1\162\2\7"+
    "\1\162\3\7\3\0\1\7\3\0\2\7\7\0\2\7"+
    "\13\0\12\7\6\0\15\7\1\230\11\7\3\0\1\7"+
    "\3\0\2\7\7\0\2\7\13\0\12\7\6\0\4\7"+
    "\1\162\22\7\3\0\1\7\3\0\2\7\7\0\2\7"+
    "\13\0\12\7\6\0\16\7\1\231\10\7\3\0\1\7"+
    "\3\0\2\7\7\0\2\7\13\0\2\7\1\232\7\7"+
    "\6\0\27\7\3\0\1\7\3\0\2\7\7\0\2\7"+
    "\13\0\12\7\6\0\10\7\1\233\16\7\3\0\1\7"+
    "\3\0\2\7\7\0\2\7\13\0\12\7\6\0\26\7"+
    "\1\162\3\0\1\7\3\0\2\7\7\0\2\7\13\0"+
    "\2\162\4\7\2\162\2\7\6\0\27\7\3\0\1\7"+
    "\3\0\2\7\7\0\2\7\13\0\12\7\6\0\14\7"+
    "\1\172\12\7\3\0\1\7\3\0\2\7\7\0\2\7"+
    "\13\0\12\7\6\0\3\7\1\133\23\7\3\0\1\7"+
    "\3\0\2\7\7\0\2\7\13\0\12\7\6\0\24\7"+
    "\1\162\2\7\3\0\1\7\3\0\2\7\7\0\2\7"+
    "\13\0\1\7\2\162\2\7\1\162\1\7\1\162\2\7"+
    "\6\0\27\7\3\0\1\7\3\0\2\7\7\0\2\7"+
    "\13\0\12\7\6\0\14\7\1\234\12\7\3\0\1\7"+
    "\3\0\2\7\7\0\2\7\13\0\1\162\11\7\6\0"+
    "\27\7\3\0\1\7\3\0\2\7\7\0\2\7\13\0"+
    "\12\7\6\0\10\7\1\133\16\7\3\0\1\7\3\0"+
    "\2\7\7\0\2\7\13\0\12\7\6\0\1\235\26\7"+
    "\3\0\1\7\3\0\2\7\7\0\2\7\13\0\12\7"+
    "\6\0\15\7\1\162\11\7\3\0\1\7\3\0\1\7";

  private static int [] zzUnpacktrans() {
    int [] result = new int[8500];
    int offset = 0;
    offset = zzUnpacktrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpacktrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String[] ZZ_ERROR_MSG = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\3\1\1\11\1\1\1\11\1\1\5\11"+
    "\5\1\1\11\3\1\1\11\4\1\2\11\1\1\1\11"+
    "\1\1\1\11\1\0\1\11\2\1\1\11\2\1\3\0"+
    "\2\11\1\0\2\11\1\0\2\11\1\0\1\11\3\0"+
    "\15\1\1\0\1\11\2\0\1\1\1\0\3\1\1\0"+
    "\25\1\1\0\1\1\1\0\25\1\1\11\11\1\1\0"+
    "\25\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[157];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private CharSequence zzBuffer = "";

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** Number of newlines encountered up to the start of the matched text. */
  @SuppressWarnings("unused")
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  @SuppressWarnings("unused")
  protected int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  private boolean zzEOFDone;

  /* user code: */
    private TokenTypeBundle tt;
    private SharedTokenTypeBundle stt;
    public PostgresPSQLParserFlexLexer(TokenTypeBundle tt) {
        this.tt = tt;
        this.stt = tt.getSharedTokenTypes();
    }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public PostgresPSQLParserFlexLexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** Returns the maximum size of the scanner buffer, which limits the size of tokens. */
  private int zzMaxBufferLen() {
    return Integer.MAX_VALUE;
  }

  /**  Whether the scanner buffer can grow to accommodate a larger token. */
  private boolean zzCanGrow() {
    return true;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  public final int getTokenStart() {
    return zzStartRead;
  }

  public final int getTokenEnd() {
    return getTokenStart() + yylength();
  }

  public void reset(CharSequence buffer, int start, int end, int initialState) {
    zzBuffer = buffer;
    zzCurrentPos = zzMarkedPos = zzStartRead = start;
    zzAtEOF  = false;
    zzAtBOL = true;
    zzEndRead = end;
    yybegin(initialState);
  }

  /**
   * Refills the input buffer.
   *
   * @return      {@code false}, iff there was new input.
   *
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {
    return true;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final CharSequence yytext() {
    return zzBuffer.subSequence(zzStartRead, zzMarkedPos);
  }


  /**
   * Returns the character at position {@code pos} from the
   * matched text.
   *
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch.
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer.charAt(zzStartRead+pos);
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * In a wellformed scanner (no or only correct usage of
   * yypushback(int) and a match-all fallback rule) this method
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public IElementType advance() throws java.io.IOException
  {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    CharSequence zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
        return null;
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { return stt.identifier;
            }
          // fall through
          case 40: break;
          case 2:
            { return stt.whiteSpace;
            }
          // fall through
          case 41: break;
          case 3:
            { return tt.getCharacterTokenType(5);
            }
          // fall through
          case 42: break;
          case 4:
            { return tt.getCharacterTokenType(7);
            }
          // fall through
          case 43: break;
          case 5:
            { return tt.getCharacterTokenType(13);
            }
          // fall through
          case 44: break;
          case 6:
            { return stt.string;
            }
          // fall through
          case 45: break;
          case 7:
            { return tt.getCharacterTokenType(10);
            }
          // fall through
          case 46: break;
          case 8:
            { return tt.getCharacterTokenType(17);
            }
          // fall through
          case 47: break;
          case 9:
            { return tt.getCharacterTokenType(20);
            }
          // fall through
          case 48: break;
          case 10:
            { return tt.getCharacterTokenType(14);
            }
          // fall through
          case 49: break;
          case 11:
            { return tt.getCharacterTokenType(2);
            }
          // fall through
          case 50: break;
          case 12:
            { return tt.getCharacterTokenType(12);
            }
          // fall through
          case 51: break;
          case 13:
            { return tt.getCharacterTokenType(3);
            }
          // fall through
          case 52: break;
          case 14:
            { return tt.getCharacterTokenType(19);
            }
          // fall through
          case 53: break;
          case 15:
            { return stt.integer;
            }
          // fall through
          case 54: break;
          case 16:
            { return tt.getCharacterTokenType(1);
            }
          // fall through
          case 55: break;
          case 17:
            { return tt.getCharacterTokenType(18);
            }
          // fall through
          case 56: break;
          case 18:
            { return tt.getCharacterTokenType(11);
            }
          // fall through
          case 57: break;
          case 19:
            { return tt.getCharacterTokenType(4);
            }
          // fall through
          case 58: break;
          case 20:
            { return tt.getCharacterTokenType(6);
            }
          // fall through
          case 59: break;
          case 21:
            { return tt.getCharacterTokenType(0);
            }
          // fall through
          case 60: break;
          case 22:
            { return tt.getCharacterTokenType(8);
            }
          // fall through
          case 61: break;
          case 23:
            { return tt.getCharacterTokenType(15);
            }
          // fall through
          case 62: break;
          case 24:
            { return tt.getCharacterTokenType(9);
            }
          // fall through
          case 63: break;
          case 25:
            { return tt.getCharacterTokenType(21);
            }
          // fall through
          case 64: break;
          case 26:
            { return tt.getCharacterTokenType(16);
            }
          // fall through
          case 65: break;
          case 27:
            { return tt.getOperatorTokenType(5);
            }
          // fall through
          case 66: break;
          case 28:
            { return stt.lineComment;
            }
          // fall through
          case 67: break;
          case 29:
            { return tt.getOperatorTokenType(8);
            }
          // fall through
          case 68: break;
          case 30:
            { return stt.number;
            }
          // fall through
          case 69: break;
          case 31:
            { return stt.blockComment;
            }
          // fall through
          case 70: break;
          case 32:
            { return tt.getOperatorTokenType(9);
            }
          // fall through
          case 71: break;
          case 33:
            { return tt.getOperatorTokenType(6);
            }
          // fall through
          case 72: break;
          case 34:
            { return tt.getOperatorTokenType(2);
            }
          // fall through
          case 73: break;
          case 35:
            { return tt.getOperatorTokenType(4);
            }
          // fall through
          case 74: break;
          case 36:
            { return tt.getOperatorTokenType(0);
            }
          // fall through
          case 75: break;
          case 37:
            { return tt.getOperatorTokenType(7);
            }
          // fall through
          case 76: break;
          case 38:
            { return tt.getOperatorTokenType(3);
            }
          // fall through
          case 77: break;
          case 39:
            { return tt.getOperatorTokenType(1);
            }
          // fall through
          case 78: break;
          default:
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
