// Generated by JFlex 1.9.1 http://jflex.de/  (tweaked for IntelliJ platform)
// source: postgres_psql_parser.flex

package com.dbn.language.psql.dialect.postgres;

import com.dbn.language.common.SharedTokenTypeBundle;
import com.dbn.language.common.TokenTypeBundle;
import com.intellij.lexer.FlexLexer;
import com.intellij.psi.tree.IElementType;


public final class PostgresPSQLParserFlexLexer implements FlexLexer {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;
  public static final int DIV = 2;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0,  0,  0, 0
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\1\u0100\1\u0200\1\u0300\1\u0400\1\u0500\1\u0600\1\u0700"+
    "\1\u0800\1\u0900\1\u0a00\1\u0b00\1\u0c00\1\u0d00\1\u0e00\1\u0f00"+
    "\1\u1000\1\u0100\1\u1100\1\u1200\1\u1300\1\u0100\1\u1400\1\u1500"+
    "\1\u1600\1\u1700\1\u1800\1\u1900\1\u1a00\1\u1b00\1\u0100\1\u1c00"+
    "\1\u1d00\1\u1e00\12\u1f00\1\u2000\1\u2100\1\u2200\1\u1f00\1\u2300"+
    "\1\u2400\2\u1f00\31\u0100\1\u2500\126\u0100\1\u2600\1\u0100\1\u2700"+
    "\1\u2800\1\u2900\1\u2a00\1\u2b00\1\u2c00\53\u0100\1\u2d00\10\u2e00"+
    "\31\u1f00\1\u0100\1\u2f00\1\u3000\1\u0100\1\u3100\1\u3200\1\u3300"+
    "\1\u3400\1\u3500\1\u3600\1\u3700\1\u3800\1\u3900\1\u0100\1\u3a00"+
    "\1\u3b00\1\u3c00\1\u3d00\1\u3e00\1\u3f00\1\u4000\1\u4100\1\u4200"+
    "\1\u4300\1\u4400\1\u4500\1\u4600\1\u4700\1\u4800\1\u4900\1\u4a00"+
    "\1\u4b00\1\u4c00\1\u4d00\1\u4e00\1\u4f00\1\u5000\1\u5100\1\u5200"+
    "\3\u0100\1\u5300\1\u5400\1\u5500\11\u1f00\1\u5600\4\u0100\1\u5700"+
    "\16\u0100\1\u5800\2\u0100\1\u5900\32\u1f00\1\u5a00\6\u1f00\2\u0100"+
    "\1\u5b00\1\u5c00\1\u1f00\1\u5d00\1\u5e00\1\u5f00\27\u0100\1\u6000"+
    "\4\u0100\1\u6100\1\u6200\41\u1f00\1\u6300\1\u0100\1\u6400\1\u6500"+
    "\11\u1f00\1\u6600\17\u1f00\1\u6700\2\u1f00\1\u6800\1\u1f00\1\u6900"+
    "\1\u6a00\1\u1f00\1\u6b00\1\u6c00\1\u6d00\1\u6e00\2\u1f00\1\u6f00"+
    "\4\u1f00\1\u7000\1\u7100\1\u7200\1\u7300\1\u1f00\1\u7400\1\u7500"+
    "\1\u1f00\1\u7600\1\u7700\1\u7800\2\u1f00\1\u7900\1\u1f00\1\u7a00"+
    "\14\u1f00\1\u6700\4\u1f00\246\u0100\1\u7b00\20\u0100\1\u7c00\1\u7d00"+
    "\25\u0100\1\u7e00\34\u0100\1\u7f00\2\u0100\1\u8000\11\u1f00\2\u0100"+
    "\1\u8100\5\u1f00\23\u0100\1\u8200\17\u0100\1\u8300\u0adc\u1f00\1\u8400"+
    "\1\u8500\u02fe\u1f00";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\1\3\1\1\1\2\16\0\4\4"+
    "\1\1\1\5\1\6\1\7\1\10\1\11\1\4\1\12"+
    "\1\13\1\14\1\15\1\16\1\17\1\20\1\21\1\22"+
    "\12\23\1\24\1\25\1\26\1\27\1\30\1\4\1\31"+
    "\3\10\1\32\1\33\1\32\7\10\1\34\14\10\1\35"+
    "\1\4\1\36\1\4\1\10\1\4\3\10\1\32\1\33"+
    "\1\32\7\10\1\34\14\10\1\37\1\40\1\41\1\4"+
    "\6\0\1\42\32\0\2\4\4\10\4\4\1\10\2\4"+
    "\1\0\7\4\1\10\4\4\1\10\5\4\27\10\1\4"+
    "\37\10\1\4\u01ca\10\4\4\14\10\16\4\5\10\7\4"+
    "\1\10\1\4\1\10\21\4\160\0\5\10\1\4\2\10"+
    "\2\4\4\10\1\4\1\10\6\4\1\10\1\4\3\10"+
    "\1\4\1\10\1\4\24\10\1\4\123\10\1\4\213\10"+
    "\1\4\5\0\2\4\246\10\1\4\46\10\2\4\1\10"+
    "\6\4\51\10\6\4\1\10\1\4\55\0\1\4\1\0"+
    "\1\4\2\0\1\4\2\0\1\4\1\0\10\4\33\10"+
    "\4\4\4\10\15\4\6\0\5\4\1\10\4\4\13\0"+
    "\1\4\1\0\3\4\53\10\37\0\4\4\2\10\1\0"+
    "\143\10\1\4\1\10\10\0\1\4\6\0\2\10\2\0"+
    "\1\4\4\0\2\10\12\0\3\10\2\4\1\10\17\4"+
    "\1\0\1\10\1\0\36\10\33\0\2\4\131\10\13\0"+
    "\1\10\16\4\12\0\41\10\11\0\2\10\4\4\1\10"+
    "\2\4\1\0\30\10\4\0\1\10\11\0\1\10\3\0"+
    "\1\10\5\0\22\4\31\10\3\0\4\4\13\10\5\4"+
    "\30\10\1\4\6\10\1\4\2\0\5\4\11\0\52\10"+
    "\72\0\66\10\3\0\1\10\22\0\1\10\7\0\12\10"+
    "\2\0\2\4\12\0\1\4\20\10\3\0\1\4\10\10"+
    "\2\4\2\10\2\4\26\10\1\4\7\10\1\4\1\10"+
    "\3\4\4\10\2\4\1\0\1\10\7\0\2\4\2\0"+
    "\2\4\3\0\1\10\10\4\1\0\4\4\2\10\1\4"+
    "\3\10\2\0\2\4\12\0\4\10\7\4\2\10\1\4"+
    "\1\0\2\4\3\0\1\4\6\10\4\4\2\10\2\4"+
    "\26\10\1\4\7\10\1\4\2\10\1\4\2\10\1\4"+
    "\2\10\2\4\1\0\1\4\5\0\4\4\2\0\2\4"+
    "\3\0\3\4\1\0\7\4\4\10\1\4\1\10\7\4"+
    "\14\0\3\10\1\0\13\4\3\0\1\4\11\10\1\4"+
    "\3\10\1\4\26\10\1\4\7\10\1\4\2\10\1\4"+
    "\5\10\2\4\1\0\1\10\10\0\1\4\3\0\1\4"+
    "\3\0\2\4\1\10\17\4\2\10\2\0\2\4\12\0"+
    "\1\4\1\10\7\4\1\10\6\0\1\4\3\0\1\4"+
    "\10\10\2\4\2\10\2\4\26\10\1\4\7\10\1\4"+
    "\2\10\1\4\5\10\2\4\1\0\1\10\7\0\2\4"+
    "\2\0\2\4\3\0\7\4\3\0\4\4\2\10\1\4"+
    "\3\10\2\0\2\4\12\0\1\4\1\10\20\4\1\0"+
    "\1\10\1\4\6\10\3\4\3\10\1\4\4\10\3\4"+
    "\2\10\1\4\1\10\1\4\2\10\3\4\2\10\3\4"+
    "\3\10\3\4\14\10\4\4\5\0\3\4\3\0\1\4"+
    "\4\0\2\4\1\10\6\4\1\0\16\4\12\0\11\4"+
    "\1\10\6\4\5\0\10\10\1\4\3\10\1\4\27\10"+
    "\1\4\20\10\2\4\1\0\1\10\7\0\1\4\3\0"+
    "\1\4\4\0\7\4\2\0\1\4\3\10\2\4\1\10"+
    "\2\4\2\10\2\0\2\4\12\0\20\4\1\10\3\0"+
    "\1\4\10\10\1\4\3\10\1\4\27\10\1\4\12\10"+
    "\1\4\5\10\2\4\1\0\1\10\7\0\1\4\3\0"+
    "\1\4\4\0\7\4\2\0\6\4\2\10\1\4\2\10"+
    "\2\0\2\4\12\0\1\4\2\10\1\0\14\4\4\0"+
    "\11\10\1\4\3\10\1\4\51\10\2\0\1\10\7\0"+
    "\1\4\3\0\1\4\4\0\1\10\5\4\3\10\1\0"+
    "\7\4\3\10\2\0\2\4\12\0\12\4\6\10\1\4"+
    "\3\0\1\4\22\10\3\4\30\10\1\4\11\10\1\4"+
    "\1\10\2\4\7\10\3\4\1\0\4\4\6\0\1\4"+
    "\1\0\1\4\10\0\6\4\12\0\2\4\2\0\15\4"+
    "\60\10\1\0\2\10\7\0\4\4\10\10\10\0\1\4"+
    "\12\0\47\4\2\10\1\4\1\10\1\4\5\10\1\4"+
    "\30\10\1\4\1\10\1\4\12\10\1\0\2\10\11\0"+
    "\1\10\2\4\5\10\1\4\1\10\1\4\7\0\1\4"+
    "\12\0\2\4\4\10\40\4\1\10\27\4\2\0\6\4"+
    "\12\0\13\4\1\0\1\4\1\0\1\4\1\0\4\4"+
    "\2\0\10\10\1\4\44\10\4\4\24\0\1\4\2\0"+
    "\5\10\13\0\1\4\44\0\11\4\1\0\71\4\53\10"+
    "\24\0\1\10\12\0\6\4\6\10\4\0\4\10\3\0"+
    "\1\10\3\0\2\10\7\0\3\10\4\0\15\10\14\0"+
    "\1\10\17\0\2\4\46\10\1\4\1\10\5\4\1\10"+
    "\2\4\53\10\1\4\115\10\1\4\4\10\2\4\7\10"+
    "\1\4\1\10\1\4\4\10\2\4\51\10\1\4\4\10"+
    "\2\4\41\10\1\4\4\10\2\4\7\10\1\4\1\10"+
    "\1\4\4\10\2\4\17\10\1\4\71\10\1\4\4\10"+
    "\2\4\103\10\2\4\3\0\40\4\20\10\20\4\126\10"+
    "\2\4\6\10\3\4\u016c\10\2\4\21\10\1\4\32\10"+
    "\5\4\113\10\3\4\13\10\7\4\22\10\4\0\11\4"+
    "\23\10\3\0\13\4\22\10\2\0\14\4\15\10\1\4"+
    "\3\10\1\4\2\0\14\4\64\10\40\0\3\4\1\10"+
    "\3\4\2\10\1\0\2\4\12\0\41\4\17\0\6\4"+
    "\131\10\7\4\5\10\2\0\42\10\1\0\1\10\5\4"+
    "\106\10\12\4\37\10\1\4\14\0\4\4\14\0\12\4"+
    "\12\0\36\10\2\4\5\10\13\4\54\10\4\4\32\10"+
    "\6\4\12\0\46\4\27\10\5\0\4\4\65\10\12\0"+
    "\1\4\35\0\2\4\13\0\6\4\12\0\15\4\1\10"+
    "\10\4\16\0\1\4\20\0\61\4\5\0\57\10\21\0"+
    "\10\10\3\4\12\0\21\4\11\0\14\4\3\0\36\10"+
    "\15\0\2\10\12\0\54\10\16\0\14\4\44\10\24\0"+
    "\10\4\12\0\3\4\3\10\12\0\44\10\2\4\13\10"+
    "\5\4\53\10\2\4\3\10\20\4\3\0\1\4\25\0"+
    "\4\10\1\0\6\10\1\0\2\10\3\0\1\10\5\4"+
    "\300\10\100\0\26\10\2\4\6\10\2\4\46\10\2\4"+
    "\6\10\2\4\10\10\1\4\1\10\1\4\1\10\1\4"+
    "\1\10\1\4\37\10\2\4\65\10\1\4\7\10\1\4"+
    "\1\10\3\4\3\10\1\4\7\10\3\4\4\10\2\4"+
    "\6\10\4\4\15\10\5\4\3\10\1\4\7\10\16\4"+
    "\5\0\30\4\2\3\5\0\20\4\2\10\23\4\1\10"+
    "\13\4\5\0\1\4\12\0\1\4\1\10\15\4\1\10"+
    "\20\4\15\10\3\4\41\10\17\4\15\0\4\4\1\0"+
    "\3\4\14\0\21\4\1\10\4\4\1\10\2\4\12\10"+
    "\1\4\1\10\3\4\5\10\6\4\1\10\1\4\1\10"+
    "\1\4\1\10\1\4\4\10\1\4\13\10\2\4\4\10"+
    "\5\4\5\10\4\4\1\10\21\4\51\10\u0177\4\345\10"+
    "\6\4\4\10\3\0\2\10\14\4\46\10\1\4\1\10"+
    "\5\4\1\10\2\4\70\10\7\4\1\10\17\4\1\0"+
    "\27\10\11\4\7\10\1\4\7\10\1\4\7\10\1\4"+
    "\7\10\1\4\7\10\1\4\7\10\1\4\7\10\1\4"+
    "\7\10\1\4\40\0\57\4\1\10\325\4\3\10\31\4"+
    "\11\10\6\0\1\4\5\10\2\4\5\10\4\4\126\10"+
    "\2\4\2\0\2\4\3\10\1\4\132\10\1\4\4\10"+
    "\5\4\53\10\1\4\136\10\21\4\40\10\60\4\320\10"+
    "\100\4\215\10\103\4\56\10\2\4\15\10\3\4\20\10"+
    "\12\0\2\10\24\4\57\10\1\0\4\4\12\0\1\4"+
    "\37\10\2\0\120\10\2\0\45\4\11\10\2\4\147\10"+
    "\2\4\103\10\2\4\2\10\1\4\1\10\1\4\10\10"+
    "\25\4\20\10\1\0\3\10\1\0\4\10\1\0\27\10"+
    "\5\0\4\4\1\0\13\4\1\10\7\4\64\10\14\4"+
    "\2\0\62\10\22\0\12\4\12\0\6\4\22\0\6\10"+
    "\3\4\1\10\1\4\2\10\13\0\34\10\10\0\2\4"+
    "\27\10\15\0\14\4\35\10\3\4\4\0\57\10\16\0"+
    "\16\4\1\10\12\0\6\4\5\10\1\0\12\10\12\0"+
    "\5\10\1\4\51\10\16\0\11\4\3\10\1\0\10\10"+
    "\2\0\2\4\12\0\6\4\27\10\3\4\1\10\3\0"+
    "\62\10\1\0\1\10\3\0\2\10\2\0\5\10\2\0"+
    "\1\10\1\0\1\10\30\4\3\10\2\4\13\10\5\0"+
    "\2\4\3\10\2\0\12\4\6\10\2\4\6\10\2\4"+
    "\6\10\11\4\7\10\1\4\7\10\1\4\53\10\1\4"+
    "\16\10\6\4\163\10\10\0\1\4\2\0\2\4\12\0"+
    "\6\4\244\10\14\4\27\10\4\4\61\10\4\4\u0100\3"+
    "\156\10\2\4\152\10\46\4\7\10\14\4\5\10\5\4"+
    "\1\10\1\0\12\10\1\4\15\10\1\4\5\10\1\4"+
    "\1\10\1\4\2\10\1\4\2\10\1\4\154\10\41\4"+
    "\153\10\22\4\100\10\2\4\66\10\50\4\15\10\3\4"+
    "\20\0\20\4\20\0\3\4\2\10\30\4\3\10\31\4"+
    "\1\10\6\4\5\10\1\4\207\10\2\4\1\0\4\4"+
    "\1\10\13\4\12\0\7\4\32\10\4\4\1\10\1\4"+
    "\32\10\13\4\131\10\3\4\6\10\2\4\6\10\2\4"+
    "\6\10\2\4\3\10\3\4\2\10\3\4\2\10\22\4"+
    "\3\0\4\4\14\10\1\4\32\10\1\4\23\10\1\4"+
    "\2\10\1\4\17\10\2\4\16\10\42\4\173\10\105\4"+
    "\65\10\210\4\1\0\202\4\35\10\3\4\61\10\17\4"+
    "\1\0\37\4\40\10\15\4\36\10\5\4\46\10\5\0"+
    "\5\4\36\10\2\4\44\10\4\4\10\10\1\4\5\10"+
    "\52\4\236\10\2\4\12\0\6\4\44\10\4\4\44\10"+
    "\4\4\50\10\10\4\64\10\14\4\13\10\1\4\17\10"+
    "\1\4\7\10\1\4\2\10\1\4\13\10\1\4\17\10"+
    "\1\4\7\10\1\4\2\10\3\4\64\10\14\4\67\10"+
    "\11\4\26\10\12\4\10\10\30\4\6\10\1\4\52\10"+
    "\1\4\11\10\105\4\6\10\2\4\1\10\1\4\54\10"+
    "\1\4\2\10\3\4\1\10\2\4\27\10\12\4\27\10"+
    "\11\4\37\10\101\4\23\10\1\4\2\10\12\4\26\10"+
    "\12\4\32\10\106\4\70\10\6\4\2\10\100\4\1\10"+
    "\3\0\1\4\2\0\5\4\4\0\4\10\1\4\3\10"+
    "\1\4\35\10\2\4\3\0\4\4\1\0\40\4\35\10"+
    "\3\4\35\10\43\4\10\10\1\4\34\10\2\0\31\4"+
    "\66\10\12\4\26\10\12\4\23\10\15\4\22\10\156\4"+
    "\111\10\67\4\63\10\15\4\63\10\15\4\44\10\4\0"+
    "\10\4\12\0\6\4\12\0\34\10\3\4\5\0\1\4"+
    "\27\10\372\4\52\10\1\4\2\0\3\4\2\10\20\4"+
    "\3\10\67\4\4\0\35\10\12\4\1\10\10\4\26\10"+
    "\13\0\37\4\22\10\4\0\52\4\25\10\33\4\27\10"+
    "\11\4\3\0\65\10\17\0\37\4\13\0\2\10\2\0"+
    "\1\10\11\4\4\0\55\10\13\0\2\4\1\0\4\4"+
    "\1\0\12\4\1\0\2\4\31\10\7\4\12\0\6\4"+
    "\3\0\44\10\16\0\1\4\12\0\4\4\1\10\2\0"+
    "\1\10\10\4\43\10\1\0\2\4\1\10\11\4\3\0"+
    "\60\10\16\0\4\10\4\4\4\0\1\4\14\0\1\10"+
    "\1\4\1\10\43\4\22\10\1\4\31\10\14\0\6\4"+
    "\1\0\2\10\1\0\76\4\7\10\1\4\1\10\1\4"+
    "\4\10\1\4\17\10\1\4\12\10\7\4\57\10\14\0"+
    "\5\4\12\0\6\4\4\0\1\4\10\10\2\4\2\10"+
    "\2\4\26\10\1\4\7\10\1\4\2\10\1\4\5\10"+
    "\1\4\2\0\1\10\7\0\2\4\2\0\2\4\3\0"+
    "\2\4\1\10\6\4\1\0\5\4\5\10\2\0\2\4"+
    "\7\0\3\4\5\0\13\4\12\10\1\4\1\10\2\4"+
    "\1\10\1\4\46\10\1\4\1\10\11\0\1\4\1\0"+
    "\2\4\1\0\1\4\4\0\1\4\5\0\1\10\1\0"+
    "\1\10\15\4\2\0\35\4\65\10\22\0\4\10\5\4"+
    "\12\0\4\4\1\0\3\10\36\4\60\10\24\0\2\10"+
    "\1\4\1\10\10\4\12\0\246\4\57\10\7\0\2\4"+
    "\11\0\27\4\4\10\2\0\42\4\60\10\21\0\3\4"+
    "\1\10\13\4\12\0\46\4\53\10\15\0\1\10\7\4"+
    "\12\0\6\4\24\0\34\4\33\10\2\4\17\0\4\4"+
    "\12\0\6\4\7\10\271\4\54\10\17\0\145\4\100\10"+
    "\12\0\25\4\10\10\2\4\1\10\2\4\10\10\1\4"+
    "\2\10\1\4\30\10\6\0\1\4\2\0\2\4\4\0"+
    "\1\10\1\0\1\10\2\0\14\4\12\0\106\4\10\10"+
    "\2\4\47\10\7\0\2\4\7\0\1\10\1\4\1\10"+
    "\1\0\33\4\1\10\12\0\50\10\7\0\1\10\4\0"+
    "\10\4\1\0\10\4\1\10\13\0\56\10\20\0\3\4"+
    "\1\10\22\4\111\10\307\4\41\10\17\4\12\0\6\4"+
    "\11\10\1\4\45\10\10\0\1\4\10\0\1\10\17\4"+
    "\12\0\30\4\36\10\2\4\26\0\1\4\16\0\111\4"+
    "\7\10\1\4\2\10\1\4\46\10\6\0\3\4\1\0"+
    "\1\4\2\0\1\4\7\0\1\10\1\0\10\4\12\0"+
    "\6\4\6\10\1\4\2\10\1\4\40\10\5\0\1\4"+
    "\2\0\1\4\5\0\1\10\7\4\12\0\u0136\4\23\10"+
    "\4\0\11\4\2\0\1\10\1\0\15\10\1\4\42\10"+
    "\7\0\3\4\5\0\15\4\13\0\125\4\1\10\54\4"+
    "\4\10\37\4\232\10\146\4\157\10\21\4\304\10\u014c\4"+
    "\141\10\17\4\60\10\21\0\6\10\17\0\12\4\u019b\10"+
    "\5\4\107\10\271\4\36\10\34\0\306\4\71\10\7\4"+
    "\37\10\1\4\12\0\6\4\117\10\1\4\12\0\6\4"+
    "\36\10\2\4\5\0\13\4\60\10\7\0\11\4\4\10"+
    "\14\4\12\0\11\4\25\10\5\4\23\10\260\4\55\10"+
    "\3\4\12\0\306\4\100\10\200\4\113\10\4\4\1\0"+
    "\1\10\67\0\7\4\4\0\15\10\100\4\2\10\1\4"+
    "\1\10\1\0\13\4\2\0\16\4\370\10\10\4\326\10"+
    "\51\4\12\10\u01e7\4\4\10\1\4\7\10\1\4\2\10"+
    "\1\4\43\10\17\4\1\10\35\4\3\10\2\4\1\10"+
    "\16\4\4\10\10\4\u018c\10\4\4\153\10\5\4\15\10"+
    "\3\4\11\10\7\4\12\10\3\4\2\0\1\4\4\0"+
    "\u014c\4\12\0\6\4\56\0\2\4\27\0\u011e\4\5\0"+
    "\3\4\26\0\2\4\7\0\36\4\4\0\224\4\3\0"+
    "\273\4\125\10\1\4\107\10\1\4\2\10\2\4\1\10"+
    "\2\4\2\10\2\4\4\10\1\4\14\10\1\4\1\10"+
    "\1\4\7\10\1\4\101\10\1\4\4\10\2\4\10\10"+
    "\1\4\7\10\1\4\34\10\1\4\4\10\1\4\5\10"+
    "\1\4\1\10\3\4\7\10\1\4\u0154\10\2\4\31\10"+
    "\1\4\31\10\1\4\37\10\1\4\31\10\1\4\37\10"+
    "\1\4\31\10\1\4\37\10\1\4\31\10\1\4\37\10"+
    "\1\4\31\10\1\4\10\10\2\4\151\0\4\4\62\0"+
    "\10\4\1\0\16\4\1\0\26\4\5\0\1\4\17\0"+
    "\120\4\37\10\6\4\6\10\325\4\7\0\1\4\21\0"+
    "\2\4\7\0\1\4\2\0\1\4\5\0\5\4\76\10"+
    "\41\4\1\0\160\4\55\10\3\4\7\0\7\10\2\4"+
    "\12\0\4\4\1\10\u0141\4\36\10\1\0\21\4\54\10"+
    "\16\0\5\4\1\10\320\4\34\10\16\0\326\4\36\10"+
    "\2\0\1\10\12\0\345\4\7\10\1\4\4\10\1\4"+
    "\2\10\1\4\17\10\1\4\305\10\13\4\7\0\51\4"+
    "\104\10\7\0\1\10\4\4\12\0\u0156\4\1\10\117\4"+
    "\4\10\1\4\33\10\1\4\2\10\1\4\1\10\2\4"+
    "\1\10\1\4\12\10\1\4\4\10\1\4\1\10\1\4"+
    "\1\10\6\4\1\10\4\4\1\10\1\4\1\10\1\4"+
    "\1\10\1\4\3\10\1\4\2\10\1\4\1\10\2\4"+
    "\1\10\1\4\1\10\1\4\1\10\1\4\1\10\1\4"+
    "\1\10\1\4\2\10\1\4\1\10\2\4\4\10\1\4"+
    "\7\10\1\4\4\10\1\4\4\10\1\4\1\10\1\4"+
    "\12\10\1\4\21\10\5\4\3\10\1\4\5\10\1\4"+
    "\21\10\104\4\340\10\40\4\72\10\6\4\336\10\2\4"+
    "\u0182\10\16\4\u0131\10\17\4\156\10\242\4\36\10\342\4"+
    "\113\10\5\4\u0160\10\121\4\1\0\36\4\140\0\200\4"+
    "\360\0\20\4";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[34304];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\4\1\5\1\1\1\6"+
    "\1\7\1\10\1\11\1\12\1\13\1\14\1\15\1\16"+
    "\1\17\1\20\1\21\1\22\1\23\1\24\1\25\1\26"+
    "\1\1\1\27\1\30\1\31\1\32\1\33\1\0\1\34"+
    "\1\4\1\7\1\35\1\36\1\37\1\40\3\0\1\41"+
    "\1\42\1\0\1\43\1\44\1\0\1\45\1\46\1\0"+
    "\1\47\1\0\1\50\2\0\1\40\1\0\1\20\1\37"+
    "\1\0\1\37\1\0\1\40";

  private static int [] zzUnpackAction() {
    int [] result = new int[63];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\43\0\106\0\151\0\214\0\43\0\257\0\43"+
    "\0\322\0\43\0\43\0\43\0\43\0\43\0\365\0\u0118"+
    "\0\u013b\0\u015e\0\u0181\0\43\0\u01a4\0\u01c7\0\u01ea\0\43"+
    "\0\u020d\0\43\0\43\0\43\0\u0230\0\43\0\151\0\43"+
    "\0\43\0\u0253\0\u0276\0\43\0\u0299\0\u02bc\0\u02df\0\u0302"+
    "\0\u0325\0\43\0\43\0\u01a4\0\43\0\43\0\u01c7\0\43"+
    "\0\43\0\u01ea\0\43\0\u0230\0\43\0\u0348\0\u036b\0\u038e"+
    "\0\u03b1\0\u03d4\0\u0348\0\u03f7\0\u03f7\0\u041a\0\43";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[63];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length() - 1;
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpacktrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\2\3\1\0\1\2\1\4\1\5\1\6\1\7"+
    "\1\10\1\11\1\12\1\13\1\14\1\15\1\16\1\17"+
    "\1\20\1\21\1\22\1\23\1\24\1\25\1\26\1\27"+
    "\1\30\2\7\1\31\1\32\1\33\1\34\1\35\1\36"+
    "\45\0\2\3\41\0\2\37\24\0\1\40\13\0\6\5"+
    "\1\41\34\5\1\7\6\0\2\7\12\0\1\7\6\0"+
    "\3\7\5\0\1\7\12\11\1\42\30\11\20\0\1\43"+
    "\43\0\1\44\1\0\1\45\34\0\1\46\46\0\1\47"+
    "\1\0\1\22\7\0\1\50\10\0\2\51\21\0\1\52"+
    "\2\0\1\53\14\0\2\54\24\0\1\55\1\56\13\0"+
    "\2\57\24\0\1\60\1\61\13\0\2\62\24\0\1\63"+
    "\13\0\1\7\6\0\2\7\1\0\1\11\10\0\1\7"+
    "\6\0\3\7\5\0\1\7\1\0\2\64\35\0\1\65"+
    "\14\0\1\11\30\0\2\43\1\0\40\43\23\0\1\45"+
    "\6\0\1\66\1\67\7\0\43\70\23\0\1\45\35\0"+
    "\1\71\1\0\1\71\2\0\1\72\20\0\2\51\24\0"+
    "\1\53\14\0\2\73\56\0\1\74\1\0\1\74\2\0"+
    "\1\75\17\0\15\70\1\76\25\70\23\0\1\72\40\0"+
    "\1\47\1\0\1\72\42\0\1\75\17\0\15\70\1\76"+
    "\4\70\1\77\20\70";

  private static int [] zzUnpacktrans() {
    int [] result = new int[1085];
    int offset = 0;
    offset = zzUnpacktrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpacktrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String[] ZZ_ERROR_MSG = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\3\1\1\11\1\1\1\11\1\1\5\11"+
    "\5\1\1\11\3\1\1\11\1\1\3\11\1\1\1\11"+
    "\1\0\2\11\2\1\1\11\2\1\3\0\2\11\1\0"+
    "\2\11\1\0\2\11\1\0\1\11\1\0\1\11\2\0"+
    "\1\1\1\0\2\1\1\0\1\1\1\0\1\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[63];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private CharSequence zzBuffer = "";

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** Number of newlines encountered up to the start of the matched text. */
  @SuppressWarnings("unused")
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  @SuppressWarnings("unused")
  protected int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  private boolean zzEOFDone;

  /* user code: */
    private TokenTypeBundle tt;
    private SharedTokenTypeBundle stt;
    public PostgresPSQLParserFlexLexer(TokenTypeBundle tt) {
        this.tt = tt;
        this.stt = tt.getSharedTokenTypes();
    }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public PostgresPSQLParserFlexLexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** Returns the maximum size of the scanner buffer, which limits the size of tokens. */
  private int zzMaxBufferLen() {
    return Integer.MAX_VALUE;
  }

  /**  Whether the scanner buffer can grow to accommodate a larger token. */
  private boolean zzCanGrow() {
    return true;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  public final int getTokenStart() {
    return zzStartRead;
  }

  public final int getTokenEnd() {
    return getTokenStart() + yylength();
  }

  public void reset(CharSequence buffer, int start, int end, int initialState) {
    zzBuffer = buffer;
    zzCurrentPos = zzMarkedPos = zzStartRead = start;
    zzAtEOF  = false;
    zzAtBOL = true;
    zzEndRead = end;
    yybegin(initialState);
  }

  /**
   * Refills the input buffer.
   *
   * @return      {@code false}, iff there was new input.
   *
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {
    return true;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final CharSequence yytext() {
    return zzBuffer.subSequence(zzStartRead, zzMarkedPos);
  }


  /**
   * Returns the character at position {@code pos} from the
   * matched text.
   *
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch.
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer.charAt(zzStartRead+pos);
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * In a wellformed scanner (no or only correct usage of
   * yypushback(int) and a match-all fallback rule) this method
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public IElementType advance() throws java.io.IOException
  {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    CharSequence zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
        return null;
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { return stt.identifier;
            }
          // fall through
          case 41: break;
          case 2:
            { return stt.whiteSpace;
            }
          // fall through
          case 42: break;
          case 3:
            { return tt.getCharacterTokenType(5);
            }
          // fall through
          case 43: break;
          case 4:
            { return stt.quotedIdentifier;
            }
          // fall through
          case 44: break;
          case 5:
            { return tt.getCharacterTokenType(7);
            }
          // fall through
          case 45: break;
          case 6:
            { return tt.getCharacterTokenType(13);
            }
          // fall through
          case 46: break;
          case 7:
            { return stt.string;
            }
          // fall through
          case 47: break;
          case 8:
            { return tt.getCharacterTokenType(10);
            }
          // fall through
          case 48: break;
          case 9:
            { return tt.getCharacterTokenType(17);
            }
          // fall through
          case 49: break;
          case 10:
            { return tt.getCharacterTokenType(20);
            }
          // fall through
          case 50: break;
          case 11:
            { return tt.getCharacterTokenType(14);
            }
          // fall through
          case 51: break;
          case 12:
            { return tt.getCharacterTokenType(2);
            }
          // fall through
          case 52: break;
          case 13:
            { return tt.getCharacterTokenType(12);
            }
          // fall through
          case 53: break;
          case 14:
            { return tt.getCharacterTokenType(3);
            }
          // fall through
          case 54: break;
          case 15:
            { return tt.getCharacterTokenType(19);
            }
          // fall through
          case 55: break;
          case 16:
            { return stt.integer;
            }
          // fall through
          case 56: break;
          case 17:
            { return tt.getCharacterTokenType(1);
            }
          // fall through
          case 57: break;
          case 18:
            { return tt.getCharacterTokenType(18);
            }
          // fall through
          case 58: break;
          case 19:
            { return tt.getCharacterTokenType(11);
            }
          // fall through
          case 59: break;
          case 20:
            { return tt.getCharacterTokenType(4);
            }
          // fall through
          case 60: break;
          case 21:
            { return tt.getCharacterTokenType(6);
            }
          // fall through
          case 61: break;
          case 22:
            { return tt.getCharacterTokenType(0);
            }
          // fall through
          case 62: break;
          case 23:
            { return tt.getCharacterTokenType(8);
            }
          // fall through
          case 63: break;
          case 24:
            { return tt.getCharacterTokenType(15);
            }
          // fall through
          case 64: break;
          case 25:
            { return tt.getCharacterTokenType(9);
            }
          // fall through
          case 65: break;
          case 26:
            { return tt.getCharacterTokenType(21);
            }
          // fall through
          case 66: break;
          case 27:
            { return tt.getCharacterTokenType(16);
            }
          // fall through
          case 67: break;
          case 28:
            { return tt.getOperatorTokenType(5);
            }
          // fall through
          case 68: break;
          case 29:
            { return stt.lineComment;
            }
          // fall through
          case 69: break;
          case 30:
            { return tt.getOperatorTokenType(8);
            }
          // fall through
          case 70: break;
          case 31:
            { return stt.number;
            }
          // fall through
          case 71: break;
          case 32:
            { return stt.blockComment;
            }
          // fall through
          case 72: break;
          case 33:
            { return tt.getOperatorTokenType(9);
            }
          // fall through
          case 73: break;
          case 34:
            { return tt.getOperatorTokenType(6);
            }
          // fall through
          case 74: break;
          case 35:
            { return tt.getOperatorTokenType(2);
            }
          // fall through
          case 75: break;
          case 36:
            { return tt.getOperatorTokenType(4);
            }
          // fall through
          case 76: break;
          case 37:
            { return tt.getOperatorTokenType(0);
            }
          // fall through
          case 77: break;
          case 38:
            { return tt.getOperatorTokenType(7);
            }
          // fall through
          case 78: break;
          case 39:
            { return tt.getOperatorTokenType(3);
            }
          // fall through
          case 79: break;
          case 40:
            { return tt.getOperatorTokenType(1);
            }
          // fall through
          case 80: break;
          default:
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
